import type { StoryBeat } from './types';

export const storyBeats: StoryBeat[] = [
  {
    id: 'algebra-avengers-intro',
    pathSlug: 'algebra-avengers',
    sequence: 1,
    context: 'path',
    title: 'The Order of the Olympiad has fallen',
    narrative: [
      'Archimedes slumps on the hard, cold floor of a dungeon at ‘The Blackhouse’.',
      'Each breath is a painful effort now.  He knows the end is nigh.',
      'The Red Baron stands over him, smirking menacingly. "Not so rational or logical now are you old man.  Fool!"',
      '"So naive. So stupid. Your stones of Logic, Rigor, Curiosity and Persistence will be mine soon enough.  Your order is finished!"',
      'The Red Baron ticks an item off his checklist and slinks into the shadows',
      'Archimedes falls down onto his side.  "The rational mind is never gone ... it can rest, but is never defeated.  Others will come.  All shall be restored."',
      'And with that, the great man exhales for the last time.',
    ],
    image: '/story/algebraic-avengers/beat_1.png',
    imageAlt: 'Archimedes dies.',
    caption: 'The greatest mathematician of antiquity is dead. Irrationality reigns.',
  },
  {
    id: 'algebra-avengers-problem-1',
    pathSlug: 'algebra-avengers',
    sequence: 2,
    context: 'problem',
    problemOrder: 1,
    problemId: 'algebra-avengers-basic-1-problem-1',
    title: 'Carl Friedrich Gauss',
    narrative: [
      'The dust swirls in the long silence. A cool breeze floats through the stable, gently tugging Carl Friedrich Gauss back into the present.',
      '"How is that possible? The realm cannot go on without The Order ... without Archimedes.  What are we to do? Chaos will consume us all!"',
      'Sir Euler listens calmly to his young protege. The aging Knight has no answers. But he knows they will come.',
      '"The Red Baron is stronger than we realised. Stronger than we ever feared possible. Our agents are searching for more information about the Stones of Enlightment as we speak."',
      '"But do not fear Carl Friedrich. Be calm. Be vigilant. Our path will appear ... when we are ready to see it."',
    ],
    image: '/story/algebraic-avengers/beat_2.png',
    imageAlt: 'Introducing Carl Friedrich.',
    caption: 'Powerful emotions stir as the young squire learns of the fall of the Order of the Olympiad.',
  },
  {
    id: 'algebra-avengers-problem-2',
    pathSlug: 'algebra-avengers',
    sequence: 3,
    context: 'problem',
    problemOrder: 2,
    problemId: 'algebra-avengers-basic-1-problem-2',
    title: 'Princess Emmy Noether',
    narrative: [
      '"Some answers must lie in here", Emmy sighed.  6 hours had passed since she entered to library since learning of death of Archimedes.',
      '"I will not rest until I find some understanding". What was this ‘Order of the Olympiad‘? What was its purpose and why had the Red Baron sought to destroy it.',
      'Emmy was the only child of King Thales and Queen Mathilde. She was 1st in line to the throne and her life felt like a series of formal functions and rules of etiquitte.',
      'But mathematics had always been her passion ever since she could remember. She soaked up all she could from he daily sessions with her tutor, Ms. Kovalevskaya.',
      'And now she felt a cool tingle of excitement. The moment had come to apply all that she had learned.',
    ],
    image: '/story/algebraic-avengers/beat_3.png',
    imageAlt: 'Introducing Emmy.',
    caption: 'Princess Emmy pores over a weighty, dusty tome ... The Paths of the Order by Archimedes of Syracuse.',
  },
  {
    id: 'algebra-avengers-problem-3',
    pathSlug: 'algebra-avengers',
    sequence: 4,
    context: 'problem',
    problemOrder: 3,
    problemId: 'algebra-avengers-basic-1-problem-3',
    title: 'The squire is summoned.',
    narrative: [
      '"Apologies for the late hour Squire Gauss.  She said you must come immediately."',
      'Carl Friedrich was just about to turn in for the night when he was startled by 2 men carrying torches entering the stable.',
      'He had been provided with a small cottage by Sir Euler when he took up his tutelage, however he preferred to sleep in a bunk near the horses.',
      '"The Princess? But why?", Carl stammered.',
      '"We have no answers, only orders Squire.  We apologise again, but let us make haste. She said the matter is of the utmost importance."',
      'Carl Friedrich felt a chill of anxiety. Had something happened at home? His family was reliant on his meagre wages and they had foregone much to get him to this position. Every day had been a struggle since Carl‘s father died.',
      '"Understood.  I will be ready in 2 moments."',
    ],
    image: '/story/algebraic-avengers/beat_4.png',
    imageAlt: 'Carl Friedrich called to the castle.',
    caption: 'Carl Friedrich is startled at the stables.',
  },
  {
    id: 'algebra-avengers-problem-4',
    pathSlug: 'algebra-avengers',
    sequence: 5,
    context: 'problem',
    problemOrder: 4,
    problemId: 'algebra-avengers-basic-1-problem-4',
    title: 'A midnight meeting.',
    narrative: [
      '"Yes, he is on his way My Lady."',
      '"Time is of the essence Ladbrook. How can it take this long!", Emmy said impatiently.',
      '"They will be here shortly My Lady. The creek down near the top stables flooded last week. It is slow going through there."',
      'Emmy paced back and forth in front of the old chapel‘s steps. Today felt like a blur. Nothing would come into focus.',
      '"Why on earth would the name of a poorly uneducated Squire of low blood be scribbled in a margin on the 3rd last page of the book?", she thought to herself.',
      'As this question siwrled around and around in her mind, the faint sound of footsteps could be heard. Then 3 men came around the corner and entered the cloister. One of them was a rather scruffy, scared looking lad whose forehead glistened with sweat.',
      'Emmy felt her jaw clench. "Surely not", she mumbled under her breath.',
    ],
    image: '/story/algebraic-avengers/beat_5.png',
    imageAlt: 'Princess Emmy waits for Carl Friedrich.',
    caption: 'Princess Emmy paces back and forward impatiently just outside the chapel.',
  },
  {
    id: 'algebra-avengers-problem-5',
    pathSlug: 'algebra-avengers',
    sequence: 6,
    context: 'problem',
    problemOrder: 5,
    problemId: 'algebra-avengers-basic-1-problem-5',
    title: 'Questions ... but no answers.',
    narrative: [
      '"Thank you for coming Squire Gauss. This matter is most urgent."',
      '"Happy to be of service My Lady. No hour is too late", Carl Friedrich lied.',
      '"Let me get to the point.", Emmy said curtly, handing Carl a book entitled ‘The Order of Olympiad‘.',
      '"Why does your name appear in hand-written in this book? Page 441.", she enquired impatiently.',
      '"No idea", Carl stammered nervously.  "I have never seen this book before."  He glanced down at the beatifully written text on its leather cover. "The Order the Olympiad?"',
      '"You know of it?", Emmy probed.',
      '"Yes. And I know that Archimedes was captured during the winter and has now died. I know the Order has fallen. Sir Euler told me this afternoon.  But I have never seen this book. My father taught me of the Order when I was a boy."',
      'Emmy was silent. She gathered her thoughts. Could she believe this boy. This young man. He seemed honest.',
      '"Ok.", she replied. She would play her cards close to her chest and try to catch him flinch. "What do you know of mathematics?"',
    ],
    image: '/story/algebraic-avengers/beat_6.png',
    imageAlt: 'Princess Emmy questions for Carl Friedrich.',
    caption: 'Princess Emmy questions Carl Friedrich about the appearance of his name in the Order of Olympiad.',
  },
  {
    id: 'algebra-avengers-problem-6',
    pathSlug: 'algebra-avengers',
    sequence: 7,
    context: 'problem',
    problemOrder: 6,
    problemId: 'algebra-avengers-basic-1-problem-6',
    title: 'A strange sense of connection.',
    narrative: [
      'Carl Friedrich walks alone under the moonlight, his boots crunching softly against the gravel path. The air is cool, and the night insects sing along the stream beside him.',
      'His thoughts race, replaying the strange encounter with Princess Emmy. “She was holding something back,” he murmurs, brow furrowed. “What on earth does that book have to do with me? I never even met Archimedes … all I know of him and the Order is what my father taught me during our lessons."',
      'Crossing the small stone bridge leading back to the stables, Carl feels a shiver course through him, not from the night air but from a strange, heavy sense of connection - like unseen eyes watching, or an echo of Archimedes’ presence carried in the current below. The moonlight glimmers on the water as if whispering secrets he cannot yet understand.',

    ],
    image: '/story/algebraic-avengers/beat_7.png',
    imageAlt: 'Carl Friedrich walks home, thoughts swirling through this mind.',
    caption: 'Carl Friedrich walks home, thoughts swirling through this mind.',
  },
  {
    id: 'algebra-avengers-problem-7',
    pathSlug: 'algebra-avengers',
    sequence: 8,
    context: 'problem',
    problemOrder: 7,
    problemId: 'algebra-avengers-basic-1-problem-7',
    title: 'A fight for reason?',
    narrative: [
      'The first light of dawn creeps into the stable yard, pale and cold. Carl Friedrich rises after a restless night, his mind still crowded with questions. He moves with quiet purpose, leading Thunder - the proud steed of Sir Euler - into the aisle. The horse snorts gently, steam rising from its nostrils in the morning chill, as Carl rubs him down with steady strokes.',
      'As his hands work the brush through Thunder’s coat, Carl drifts back to memories of his father. Long evenings bent over parchment, ink smudged on their fingers, as they worked through mathematical problems by candlelight. His father’s eyes always burned with something more than simple curiosity - something Carl only half understood. Each lesson carried a story of the Order of the Olympiad, of Archimedes’ daring, of the struggle to preserve reason.',
      '“Fight for reason. Defend rationality, son,” his father had always insisted, voice steady with conviction. Carl remembered smiling at the time, thinking it was nothing more than romantic idealism. But now, in the quiet dawn, with the strange weight of Emmy’s summons still pressing on him, those words seemed less fanciful - and more like a warning.',

    ],
    image: '/story/algebraic-avengers/beat_8.png',
    imageAlt: 'Carl Friedrich remembers.',
    caption: 'Carl Friedrich is lost in this thoughts. Recalling his father’s words.',
  },
  {
    id: 'algebra-avengers-problem-8',
    pathSlug: 'algebra-avengers',
    sequence: 9,
    context: 'problem',
    problemOrder: 8,
    problemId: 'algebra-avengers-basic-1-problem-8',
    title: 'A father’s farewell.',
    narrative: [
      'A light rain falls as mourners gather in the small churchyard. Dorothea Gauss clutches her shawl, her eyes red with grief as she and her family stand beside the casket. Father Ceva offers words of comfort, his voice solemn under the gray sky.',
      'Carl stares at the coffin of his father, Gebhard Gauss—a stern man who rarely showed affection, yet whose sudden passing left a void too deep to measure. Beside him, Uncle Friedrich bows his head, the Duke of Brunswick’s support behind him, but even that seemed fragile against the weight of loss.',
      'Carl’s mind drifts as rain collects on his mat of brown hair and dampens his coat. His father’s words echo again: “Fight for reason. Defend rationality, son.” For the first time, Carl does not dismiss them as romantic ideals. He feels the charge settle on his shoulders, heavy and inescapable. “Yes, Father,” he whispers silently, “I will.”',
    ],
    image: '/story/algebraic-avengers/beat_9.png',
    imageAlt: 'Carl Friedrich at his father’s funeral.',
    caption: 'Carl remembers his father’s final lesson as the rain falls.',
  },
  {
    id: 'algebra-avengers-problem-9',
    pathSlug: 'algebra-avengers',
    sequence: 10,
    context: 'problem',
    problemOrder: 9,
    problemId: 'algebra-avengers-basic-1-problem-9',
    title: 'A mystery visitor.',
    narrative: [
      'Carl and Dorothea sat at the kitchen table after the funeral. Their modest home was tidy and cosy, yet tonight it felt heavy with silence. The only sound was the faint tick of the wall clock.',
      '"Mother, did Father always have such a passion for mathematics?" Carl asked quietly. "He was so driven with his lessons. I never really understood why."',
      'Dorothea shook her head gently. "Oh no, dear. Your father was a simple man. It all changed after that strange gentleman visited us, when you were barely able to walk. Soon after, he began borrowing all sorts of books on mathematics from the library."',
      '"Books?" Carl frowned.',
      '"Yes. I asked him why, and he only smiled and said it was to strengthen his reasoning. He never spoke more of it, but I saw a fire in him I had never seen before."',
      'Carl lifted his teacup, staring into the dark liquid. He drank slowly, but the warmth did little to ease the chill of new questions rising within him.',
    ],
    image: '/story/algebraic-avengers/beat_10.png',
    imageAlt: 'Carl and his mother Dorothea at the kitchen table.',
    caption: 'Dorothea recalls the mysterious visitor who sparked Gebhard’s passion for mathematics.',
  },
  {
    id: 'algebra-avengers-problem-10',
    pathSlug: 'algebra-avengers',
    sequence: 11,
    context: 'problem',
    problemOrder: 10,
    problemId: 'algebra-avengers-basic-1-problem-10',
    title: 'A hidden riddle.',
    narrative: [
      'Emmy had read through every page of the great tome. Twice. After her meeting with Carl Friedrich, she could think of nothing else. “I know this is important… but why?” she whispered. For hours she had traced the passages about the Order and their devotion to problem-solving, yet nowhere did it explain why the name of a Squire Gauss was scrawled in its margin.',
      'Her eyes burned with fatigue. With a sigh, she closed the heavy cover and heaved the volume back toward its place on the shelf. As she slid it into place, something shifted. A thin, rectangular slip of parchment edged its way from beneath the spine, fluttering onto the floor.',
      'Emmy bent down, heart quickening. On the slip, in faded ink, was written a riddle:',
      '“Red lies at the ratio 3:2, when all of their prayers align.”',
      'She stared at the words, a shiver running down her arms. The message was no accident. It was meant for her to find.',
    ],
    image: '/story/algebraic-avengers/beat_11.png',
    imageAlt: 'Princess Emmy in the candlelit library discovering a hidden parchment.',
    caption: 'In the quiet library, Emmy uncovers a mysterious riddle hidden in the spine of the book.',
  },
  {
    id: 'algebra-avengers-problem-11',
    pathSlug: 'algebra-avengers',
    sequence: 12,
    context: 'problem',
    problemOrder: 11,
    problemId: 'algebra-avengers-basic-1-problem-11',
    title: 'The Baron’s fury.',
    narrative: [
      '“What do you mean your men can’t find them!” The Red Baron’s voice cracked like a whip, echoing through the vaulted hall. He slammed his gauntleted hand on the oak table, the sound rattling goblets and scattering parchments. His face blazed crimson, eyes burning with fury so intense that even his lead henchman flinched.',
      '“We know he had the Stones of Enlightenment! Your scouts said they were in his possession the day before we seized him,” the Baron snarled.',
      'The henchman bowed his head, words tumbling nervously. “They were there, my Lord… but they are not there now. The place has been cleared out.”',
      'A suffocating silence followed, heavy as the storm before a thunderclap. The soldiers in the shadows dared not breathe. The Red Baron’s glare lingered on his trembling servant, the air alive with the threat of sudden, violent reprisal.'
    ],
    image: '/story/algebraic-avengers/beat_12.png',
    imageAlt: 'The Red Baron slams his hand on a war table in a vaulted hall as soldiers cower.',
    caption: 'The Red Baron’s fury fills the hall with dread.',
  },
  {
    id: 'algebra-avengers-problem-12',
    pathSlug: 'algebra-avengers',
    sequence: 13,
    context: 'problem',
    problemOrder: 12,
    problemId: 'algebra-avengers-basic-1-problem-12',
    title: 'The hunt begins.',
    narrative: [
      '“Spread out! Find the Stones! Spare no one in the search!” roared the lead henchman, his voice ragged with fear as much as fury. He slammed a fist into his palm, eyes darting nervously toward the great hall behind him.',
      '“Find them… FIND them… FIND THEM!” The words rose to a shriek, echoing against the stone walls. The men stiffened, their terror plain; none dared whisper the unthinkable—that the Stones might already be gone.',
      'Torches flared as soldiers broke ranks, scattering into the night. Boots pounded against cobblestones, shadows stretched across the courtyard, and the air reeked of desperation.'
    ],
    image: '/story/algebraic-avengers/beat_13.png',
    imageAlt: 'Soldiers in red coats scatter from the great hall courtyard at night, torches flaring.',
    caption: 'The Red Baron’s men scatter into the night, desperate to find the Stones.',
  },
  {
    id: 'algebra-avengers-problem-13',
    pathSlug: 'algebra-avengers',
    sequence: 14,
    context: 'problem',
    problemOrder: 13,
    problemId: 'algebra-avengers-basic-1-problem-13',
    title: 'Archimedes’ Last Instructions',
    narrative: [
      'Archimedes bent over his desk, quill scratching furiously across the parchment he had labored over for more than a week.',
      'Before him lay the Stones, their facets catching the candlelight — constant reminders of what was at stake. He knew the net was closing in.',
      'For years the Red Baron’s influence had spread like a shadow, and now his hunger for power had risen to a fever pitch. Only yesterday Archimedes had glimpsed two dark figures lurking beyond his cottage window at dusk, vanishing into the night when he cried out.',
      'With every stroke of the quill he prepared his final instructions, a plan to spirit the Stones away from danger. He might fall, but so long as logic and reason endured, the Order would rise again.'
    ],
    image: '/story/algebraic-avengers/beat_14.png',
    imageAlt: 'Archimedes frantically writes at his oak desk by candlelight, the four glowing Stones before him, shadowy figures faintly visible outside the window.',
    caption: 'Archimedes prepares his final instructions to safeguard the Stones, knowing the Red Baron’s net is closing in.',
  },
  {
    id: 'algebra-avengers-problem-14',
    pathSlug: 'algebra-avengers',
    sequence: 15,
    context: 'problem',
    problemOrder: 14,
    problemId: 'algebra-avengers-basic-1-problem-14',
    title: 'Manfred’s Inheritance',
    narrative: [
      'Manfred Flintz was born into privilege, the son of a powerful family of landowners. His father, Sigfried Flintz, was a domineering, heartless man who cared more for wealth than for kin or community.',
      'Through threats and intimidation, Sigfried bent political decisions in his county to his will. This was the shadow under which Manfred grew up.',
      'At school he strove tirelessly for his father’s approval, hoping that academic success might earn a word of praise. It never came.',
      '“These riddles and arithmetic nonsense serve no purpose,” Sigfried would sneer. “The only things that matter are wealth, power, and control. Something is true because we say it is — that is all the logic we need.”',
      'And so, denied recognition, Manfred turned from his love of study. Year by year, he drifted away from curiosity and reason, until at last he became his father’s mirror — a man shaped by domination, not discovery.'
    ],
    image: '/story/algebraic-avengers/beat_15.png',
    imageAlt: 'A young Manfred Flintz sits at a school desk under the looming shadow of his father Sigfried, who gestures dismissively at books and papers.',
    caption: 'Raised in the shadow of his father’s tyranny, Manfred Flintz slowly abandoned reason and became his father’s mirror.',
  },
  {
    id: 'algebra-avengers-problem-15',
    pathSlug: 'algebra-avengers',
    sequence: 16,
    context: 'problem',
    problemOrder: 15,
    problemId: 'algebra-avengers-basic-1-problem-15',
    title: 'The Riddle of the Stones',
    narrative: [
      'When Reason falters, seek the red,',
      'Three for the road and two for the end.',
      'From the church to the great cathedral,',
      'The mark lies where the ratio bends.',
      '',
      'In waters clear, the blue is bound,',
      'Five parts forward, four remain sound.',
      'The creek that runs from cottage to town,',
      'There the stone of rigor is drowned.',
      '',
      'Climb the steps where learning stays,',
      'Eleven bricks shall mark your way.',
      'Pass six before the yellow gleams,',
      'Where curiosity fuels all dreams.',
      '',
      'Fields of green where farmers sow,',
      'Along the diagonal path you go.',
      'Count seven, then the eighth to last,',
      'There persistence shall hold fast.',
      '',
      'Now guard this riddle, but let none see,',
      'Burn the letter, remember the key.',
      'For paper falls to ash and flame,',
      'Yet truth endures when held in name.'
    ],
    image: '/story/algebraic-avengers/beat_16.png',
    imageAlt: 'An ancient parchment sealed with wax, inscribed with a riddle about the four Stones.',
    caption: 'Archimedes’s letter of instruction telling its recipient hide the Stones within a riddle.',
  },
  {
    id: 'algebra-avengers-beat-17',
    pathSlug: 'algebra-avengers',
    sequence: 17,
    context: 'problem',
    problemOrder: 16,
    problemId: 'algebra-avengers-intermediate-1-problem-1',
    title: 'Father Mersenne Receives the Letter',
    narrative: [
      'Father Marin Mersenne was as much a scientist and mathematician as he was a Catholic priest.',
      'His greatest joy came from unraveling the latest mathematical puzzles, often delivered in the steady stream of letters from his many correspondents.',
      'In fact, Mersenne had become something of a clearinghouse for Europe’s thinkers — linking minds across borders, passing along conjectures, proofs, and problems.',
      'Pierre de Fermat, for example, published little, but wrote often to Mersenne, trusting him to spread ideas through his vast network.',
      '',
      'So when the priest unfolded this strange, cryptic letter from Archimedes, he hesitated.',
      'The words were dense, riddling, and unlike the usual academic queries.',
      'Had the old master finally lost his reason? Mersenne frowned, then shook his head. No… there was intent here.',
      '',
      'He leaned back in his chair, candlelight flickering against the vaulted ceiling above.',
      '"Is this a challenge? A summons? A plea for help?" he murmured.',
      'His eyes lingered on the parchment, thoughts racing.',
      'Whatever it was, Archimedes was stirring something deeper — a call that could not be ignored.'
    ],
    image: '/story/algebraic-avengers/beat_17.png',
    imageAlt: 'Father Marin Mersenne, a 1700s priest and mathematician, sits at his desk by candlelight, holding a cryptic letter with a thoughtful expression.',
    caption: 'Father Mersenne, Europe’s great communicator of ideas, receives Archimedes’s mysterious letter and wonders what it means.',
  },
  {
    "id": "algebra-avengers-beat-18",
    "pathSlug": "algebra-avengers",
    "sequence": 18,
    "context": "problem",
    problemOrder: 17,
    problemId: 'algebra-avengers-intermediate-1-problem-2',
    "title": "The Red Stone",
    "narrative": [
      "Pierre de Fermat sat in his law office, quill idle, the scent of old ink and parchment heavy in the air. Another case, another dispute over land and lineage — the kind of work that dulled the sharp edge of his mind.",
      "His thoughts drifted instead to the strange parcel delivered that morning: a small leather box containing a red stone prism, glinting faintly even in the dim light. Beneath it lay a folded letter, its seal unmarked yet pressed with uncanny precision.",
      "He unfolded it again, eyes tracing the neat, deliberate script:",
      "",
      "'When ratio bends and reason wanes,",
      "Seek the Father where the silence reigns.",
      "The prism guards what words conceal —",
      "Deliver it whole, and thought made real.'",
      "",
      "Fermat frowned, tapping the letter against his palm.",
      "'How singular? A prank from the old friar, perhaps? Or Descartes up to mischief.'",
      "A faint smile tugged at his lips. 'I could do with a break from this tedium anyhow.'",
      "",
      "He closed the leather box, slipped it into his satchel, threw on his heavy coat, and stepped out into the chill of the afternoon — unaware that the quiet corridors of the courthouse would soon feel emptier without him."
    ],
    "image": "/story/algebraic-avengers/beat_18.png",
    "imageAlt": "Pierre de Fermat, 17th-century mathematician and lawyer, sits at his desk surrounded by parchments, gazing thoughtfully at a red stone prism beside an open letter.",
    "caption": "Pierre de Fermat discovers a mysterious red stone and a cryptic verse, setting in motion a journey beyond the bounds of law and reason."
  },
  {
    "id": "algebra-avengers-beat-19",
    "pathSlug": "algebra-avengers",
    "sequence": 19,
    "context": "problem",
    "problemOrder": 18,
    "problemId": "algebra-avengers-intermediate-1-problem-3",
    "title": "The Blue Stone",
    "narrative": [
      "René Descartes was still feeling grumpy at being woken by a knock at the door. He disliked rising early, but the sharp chill of the morning air and the echo of boots in the street told him sleep was now lost for good.",
      "A courier had delivered a small, leather-bound box containing a curious blue stone — smooth, translucent, and faintly humming in the dawn light — along with a folded letter sealed in red wax.",
      "He broke the seal, eyes narrowing as he read the neat, deliberate script:",
      "",
      "'In azure bound where thought takes form,",
      "The line of truth resists the storm.",
      "Seek the priest of measured song,",
      "Where numbers hide and faith grows strong.'",
      "",
      "'Fermat, no doubt,' Descartes grumbled, tossing the page onto the table. 'That vagabond is always trying to test my patience.'",
      "",
      "He paused, staring again at the blue stone, its surface catching the faintest shimmer of candlelight.",
      "'How curious,' he murmured. 'Perhaps not Fermat.'",
      "",
      "He shuffled into the kitchen, cut himself a slice of bread, and leaned on the counter.",
      "His mind — sharp, relentless, and unwilling to rest — began to turn the verse over and over.",
      "The day would not proceed until he had untangled this riddle and the strange purpose of the stone."
    ],
    "image": "/story/algebraic-avengers/beat_19.png",
    "imageAlt": "René Descartes, 17th-century philosopher and mathematician, stands in his Amsterdam doorway as a courier hands him a small leather box containing a glowing blue stone.",
    "caption": "René Descartes receives a mysterious blue stone and a cryptic verse, hinting at a mission involving a 'priest of measured song.'"
  }
  
];
