import type { StoryBeat } from './types';

export const storyBeats: StoryBeat[] = [
  {
    id: 'algebra-avengers-intro',
    pathSlug: 'algebra-avengers',
    sequence: 1,
    context: 'path',
    title: 'The Order of the Olympiad has fallen',
    narrative: [
      'Archimedes slumps on the hard, cold floor of a dungeon at ‘The Blackhouse’.',
      'Each breath is a painful effort now.  He knows the end is nigh.',
      'The Red Baron stands over him, smirking menacingly. "Not so rational or logical now are you old man.  Fool!"',
      '"So naive. So stupid. Your stones of Logic, Rigor, Curiosity and Persistence will be mine soon enough.  Your order is finished!"',
      'The Red Baron ticks an item off his checklist and slinks into the shadows',
      'Archimedes falls down onto his side.  "The rational mind is never gone ... it can rest, but is never defeated.  Others will come.  All shall be restored."',
      'And with that, the great man exhales for the last time.',
    ],
    image: '/story/algebraic-avengers/beat_1.png',
    imageAlt: 'Archimedes dies.',
    caption: 'The greatest mathematician of antiquity is dead. Irrationality reigns.',
  },
  {
    id: 'algebra-avengers-problem-1',
    pathSlug: 'algebra-avengers',
    sequence: 2,
    context: 'problem',
    problemOrder: 1,
    problemId: 'algebra-avengers-basic-1-problem-1',
    title: 'Carl Friedrich Gauss',
    narrative: [
      'The dust swirls in the long silence. A cool breeze floats through the stable, gently tugging Carl Friedrich Gauss back into the present.',
      '"How is that possible? The realm cannot go on without The Order ... without Archimedes.  What are we to do? Chaos will consume us all!"',
      'Sir Euler listens calmly to his young protege. The aging Knight has no answers. But he knows they will come.',
      '"The Red Baron is stronger than we realised. Stronger than we ever feared possible. Our agents are searching for more information about the Stones of Enlightment as we speak."',
      '"But do not fear Carl Friedrich. Be calm. Be vigilant. Our path will appear ... when we are ready to see it."',
    ],
    image: '/story/algebraic-avengers/beat_2.png',
    imageAlt: 'Introducing Carl Friedrich.',
    caption: 'Powerful emotions stir as the young squire learns of the fall of the Order of the Olympiad.',
  },
  {
    id: 'algebra-avengers-problem-2',
    pathSlug: 'algebra-avengers',
    sequence: 3,
    context: 'problem',
    problemOrder: 2,
    problemId: 'algebra-avengers-basic-1-problem-2',
    title: 'Princess Emmy Noether',
    narrative: [
      '"Some answers must lie in here", Emmy sighed.  6 hours had passed since she entered to library since learning of death of Archimedes.',
      '"I will not rest until I find some understanding". What was this ‘Order of the Olympiad‘? What was its purpose and why had the Red Baron sought to destroy it.',
      'Emmy was the only child of King Thales and Queen Mathilde. She was 1st in line to the throne and her life felt like a series of formal functions and rules of etiquitte.',
      'But mathematics had always been her passion ever since she could remember. She soaked up all she could from he daily sessions with her tutor, Ms. Kovalevskaya.',
      'And now she felt a cool tingle of excitement. The moment had come to apply all that she had learned.',
    ],
    image: '/story/algebraic-avengers/beat_3.png',
    imageAlt: 'Introducing Emmy.',
    caption: 'Princess Emmy pores over a weighty, dusty tome ... The Paths of the Order by Archimedes of Syracuse.',
  },
  {
    id: 'algebra-avengers-problem-3',
    pathSlug: 'algebra-avengers',
    sequence: 4,
    context: 'problem',
    problemOrder: 3,
    problemId: 'algebra-avengers-basic-1-problem-3',
    title: 'The squire is summoned.',
    narrative: [
      '"Apologies for the late hour Squire Gauss.  She said you must come immediately."',
      'Carl Friedrich was just about to turn in for the night when he was startled by 2 men carrying torches entering the stable.',
      'He had been provided with a small cottage by Sir Euler when he took up his tutelage, however he preferred to sleep in a bunk near the horses.',
      '"The Princess? But why?", Carl stammered.',
      '"We have no answers, only orders Squire.  We apologise again, but let us make haste. She said the matter is of the utmost importance."',
      'Carl Friedrich felt a chill of anxiety. Had something happened at home? His family was reliant on his meagre wages and they had foregone much to get him to this position. Every day had been a struggle since Carl‘s father died.',
      '"Understood.  I will be ready in 2 moments."',
    ],
    image: '/story/algebraic-avengers/beat_4.png',
    imageAlt: 'Carl Friedrich called to the castle.',
    caption: 'Carl Friedrich is startled at the stables.',
  },
  {
    id: 'algebra-avengers-problem-4',
    pathSlug: 'algebra-avengers',
    sequence: 5,
    context: 'problem',
    problemOrder: 4,
    problemId: 'algebra-avengers-basic-1-problem-4',
    title: 'A midnight meeting.',
    narrative: [
      '"Yes, he is on his way My Lady."',
      '"Time is of the essence Ladbrook. How can it take this long!", Emmy said impatiently.',
      '"They will be here shortly My Lady. The creek down near the top stables flooded last week. It is slow going through there."',
      'Emmy paced back and forth in front of the old chapel‘s steps. Today felt like a blur. Nothing would come into focus.',
      '"Why on earth would the name of a poorly uneducated Squire of low blood be scribbled in a margin on the 3rd last page of the book?", she thought to herself.',
      'As this question siwrled around and around in her mind, the faint sound of footsteps could be heard. Then 3 men came around the corner and entered the cloister. One of them was a rather scruffy, scared looking lad whose forehead glistened with sweat.',
      'Emmy felt her jaw clench. "Surely not", she mumbled under her breath.',
    ],
    image: '/story/algebraic-avengers/beat_5.png',
    imageAlt: 'Princess Emmy waits for Carl Friedrich.',
    caption: 'Princess Emmy paces back and forward impatiently just outside the chapel.',
  },
  {
    id: 'algebra-avengers-problem-5',
    pathSlug: 'algebra-avengers',
    sequence: 6,
    context: 'problem',
    problemOrder: 5,
    problemId: 'algebra-avengers-basic-1-problem-5',
    title: 'Questions ... but no answers.',
    narrative: [
      '"Thank you for coming Squire Gauss. This matter is most urgent."',
      '"Happy to be of service My Lady. No hour is too late", Carl Friedrich lied.',
      '"Let me get to the point.", Emmy said curtly, handing Carl a book entitled ‘The Order of Olympiad‘.',
      '"Why does your name appear in hand-written in this book? Page 441.", she enquired impatiently.',
      '"No idea", Carl stammered nervously.  "I have never seen this book before."  He glanced down at the beatifully written text on its leather cover. "The Order the Olympiad?"',
      '"You know of it?", Emmy probed.',
      '"Yes. And I know that Archimedes was captured during the winter and has now died. I know the Order has fallen. Sir Euler told me this afternoon.  But I have never seen this book. My father taught me of the Order when I was a boy."',
      'Emmy was silent. She gathered her thoughts. Could she believe this boy. This young man. He seemed honest.',
      '"Ok.", she replied. She would play her cards close to her chest and try to catch him flinch. "What do you know of mathematics?"',
    ],
    image: '/story/algebraic-avengers/beat_6.png',
    imageAlt: 'Princess Emmy questions for Carl Friedrich.',
    caption: 'Princess Emmy questions Carl Friedrich about the appearance of his name in the Order of Olympiad.',
  },
  {
    id: 'algebra-avengers-problem-6',
    pathSlug: 'algebra-avengers',
    sequence: 7,
    context: 'problem',
    problemOrder: 6,
    problemId: 'algebra-avengers-basic-1-problem-6',
    title: 'A strange sense of connection.',
    narrative: [
      'Carl Friedrich walks alone under the moonlight, his boots crunching softly against the gravel path. The air is cool, and the night insects sing along the stream beside him.',
      'His thoughts race, replaying the strange encounter with Princess Emmy. “She was holding something back,” he murmurs, brow furrowed. “What on earth does that book have to do with me? I never even met Archimedes … all I know of him and the Order is what my father taught me during our lessons."',
      'Crossing the small stone bridge leading back to the stables, Carl feels a shiver course through him, not from the night air but from a strange, heavy sense of connection - like unseen eyes watching, or an echo of Archimedes’ presence carried in the current below. The moonlight glimmers on the water as if whispering secrets he cannot yet understand.',

    ],
    image: '/story/algebraic-avengers/beat_7.png',
    imageAlt: 'Carl Friedrich walks home, thoughts swirling through this mind.',
    caption: 'Carl Friedrich walks home, thoughts swirling through this mind.',
  },
  {
    id: 'algebra-avengers-problem-7',
    pathSlug: 'algebra-avengers',
    sequence: 8,
    context: 'problem',
    problemOrder: 7,
    problemId: 'algebra-avengers-basic-1-problem-7',
    title: 'A fight for reason?',
    narrative: [
      'The first light of dawn creeps into the stable yard, pale and cold. Carl Friedrich rises after a restless night, his mind still crowded with questions. He moves with quiet purpose, leading Thunder - the proud steed of Sir Euler - into the aisle. The horse snorts gently, steam rising from its nostrils in the morning chill, as Carl rubs him down with steady strokes.',
      'As his hands work the brush through Thunder’s coat, Carl drifts back to memories of his father. Long evenings bent over parchment, ink smudged on their fingers, as they worked through mathematical problems by candlelight. His father’s eyes always burned with something more than simple curiosity - something Carl only half understood. Each lesson carried a story of the Order of the Olympiad, of Archimedes’ daring, of the struggle to preserve reason.',
      '“Fight for reason. Defend rationality, son,” his father had always insisted, voice steady with conviction. Carl remembered smiling at the time, thinking it was nothing more than romantic idealism. But now, in the quiet dawn, with the strange weight of Emmy’s summons still pressing on him, those words seemed less fanciful - and more like a warning.',

    ],
    image: '/story/algebraic-avengers/beat_8.png',
    imageAlt: 'Carl Friedrich remembers.',
    caption: 'Carl Friedrich is lost in this thoughts. Recalling his father’s words.',
  },
  {
    id: 'algebra-avengers-problem-8',
    pathSlug: 'algebra-avengers',
    sequence: 9,
    context: 'problem',
    problemOrder: 8,
    problemId: 'algebra-avengers-basic-1-problem-8',
    title: 'A father’s farewell.',
    narrative: [
      'A light rain falls as mourners gather in the small churchyard. Dorothea Gauss clutches her shawl, her eyes red with grief as she and her family stand beside the casket. Father Ceva offers words of comfort, his voice solemn under the gray sky.',
      'Carl stares at the coffin of his father, Gebhard Gauss—a stern man who rarely showed affection, yet whose sudden passing left a void too deep to measure. Beside him, Uncle Friedrich bows his head, the Duke of Brunswick’s support behind him, but even that seemed fragile against the weight of loss.',
      'Carl’s mind drifts as rain collects on his mat of brown hair and dampens his coat. His father’s words echo again: “Fight for reason. Defend rationality, son.” For the first time, Carl does not dismiss them as romantic ideals. He feels the charge settle on his shoulders, heavy and inescapable. “Yes, Father,” he whispers silently, “I will.”',
    ],
    image: '/story/algebraic-avengers/beat_9.png',
    imageAlt: 'Carl Friedrich at his father’s funeral.',
    caption: 'Carl remembers his father’s final lesson as the rain falls.',
  },
  {
    id: 'algebra-avengers-problem-9',
    pathSlug: 'algebra-avengers',
    sequence: 10,
    context: 'problem',
    problemOrder: 9,
    problemId: 'algebra-avengers-basic-1-problem-9',
    title: 'A mystery visitor.',
    narrative: [
      'Carl and Dorothea sat at the kitchen table after the funeral. Their modest home was tidy and cosy, yet tonight it felt heavy with silence. The only sound was the faint tick of the wall clock.',
      '"Mother, did Father always have such a passion for mathematics?" Carl asked quietly. "He was so driven with his lessons. I never really understood why."',
      'Dorothea shook her head gently. "Oh no, dear. Your father was a simple man. It all changed after that strange gentleman visited us, when you were barely able to walk. Soon after, he began borrowing all sorts of books on mathematics from the library."',
      '"Books?" Carl frowned.',
      '"Yes. I asked him why, and he only smiled and said it was to strengthen his reasoning. He never spoke more of it, but I saw a fire in him I had never seen before."',
      'Carl lifted his teacup, staring into the dark liquid. He drank slowly, but the warmth did little to ease the chill of new questions rising within him.',
    ],
    image: '/story/algebraic-avengers/beat_10.png',
    imageAlt: 'Carl and his mother Dorothea at the kitchen table.',
    caption: 'Dorothea recalls the mysterious visitor who sparked Gebhard’s passion for mathematics.',
  },
  {
    id: 'algebra-avengers-problem-10',
    pathSlug: 'algebra-avengers',
    sequence: 11,
    context: 'problem',
    problemOrder: 10,
    problemId: 'algebra-avengers-basic-1-problem-10',
    title: 'A hidden riddle.',
    narrative: [
      'Emmy had read through every page of the great tome. Twice. After her meeting with Carl Friedrich, she could think of nothing else. “I know this is important… but why?” she whispered. For hours she had traced the passages about the Order and their devotion to problem-solving, yet nowhere did it explain why the name of a Squire Gauss was scrawled in its margin.',
      'Her eyes burned with fatigue. With a sigh, she closed the heavy cover and heaved the volume back toward its place on the shelf. As she slid it into place, something shifted. A thin, rectangular slip of parchment edged its way from beneath the spine, fluttering onto the floor.',
      'Emmy bent down, heart quickening. On the slip, in faded ink, was written a riddle:',
      '“Red lies at the ratio 3:2, when all of their prayers align.”',
      'She stared at the words, a shiver running down her arms. The message was no accident. It was meant for her to find.',
    ],
    image: '/story/algebraic-avengers/beat_11.png',
    imageAlt: 'Princess Emmy in the candlelit library discovering a hidden parchment.',
    caption: 'In the quiet library, Emmy uncovers a mysterious riddle hidden in the spine of the book.',
  },
  {
    id: 'algebra-avengers-problem-11',
    pathSlug: 'algebra-avengers',
    sequence: 12,
    context: 'problem',
    problemOrder: 11,
    problemId: 'algebra-avengers-basic-1-problem-11',
    title: 'The Baron’s fury.',
    narrative: [
      '“What do you mean your men can’t find them!” The Red Baron’s voice cracked like a whip, echoing through the vaulted hall. He slammed his gauntleted hand on the oak table, the sound rattling goblets and scattering parchments. His face blazed crimson, eyes burning with fury so intense that even his lead henchman flinched.',
      '“We know he had the Stones of Enlightenment! Your scouts said they were in his possession the day before we seized him,” the Baron snarled.',
      'The henchman bowed his head, words tumbling nervously. “They were there, my Lord… but they are not there now. The place has been cleared out.”',
      'A suffocating silence followed, heavy as the storm before a thunderclap. The soldiers in the shadows dared not breathe. The Red Baron’s glare lingered on his trembling servant, the air alive with the threat of sudden, violent reprisal.'
    ],
    image: '/story/algebraic-avengers/beat_12.png',
    imageAlt: 'The Red Baron slams his hand on a war table in a vaulted hall as soldiers cower.',
    caption: 'The Red Baron’s fury fills the hall with dread.',
  },
  {
    id: 'algebra-avengers-problem-12',
    pathSlug: 'algebra-avengers',
    sequence: 13,
    context: 'problem',
    problemOrder: 12,
    problemId: 'algebra-avengers-basic-1-problem-12',
    title: 'The hunt begins.',
    narrative: [
      '“Spread out! Find the Stones! Spare no one in the search!” roared the lead henchman, his voice ragged with fear as much as fury. He slammed a fist into his palm, eyes darting nervously toward the great hall behind him.',
      '“Find them… FIND them… FIND THEM!” The words rose to a shriek, echoing against the stone walls. The men stiffened, their terror plain; none dared whisper the unthinkable — that the Stones might already be gone.',
      'Torches flared as soldiers broke ranks, scattering into the night. Boots pounded against cobblestones, shadows stretched across the courtyard, and the air reeked of desperation.'
    ],
    image: '/story/algebraic-avengers/beat_13.png',
    imageAlt: 'Soldiers in red coats scatter from the great hall courtyard at night, torches flaring.',
    caption: 'The Red Baron’s men scatter into the night, desperate to find the Stones.',
  },
  {
    id: 'algebra-avengers-problem-13',
    pathSlug: 'algebra-avengers',
    sequence: 14,
    context: 'problem',
    problemOrder: 13,
    problemId: 'algebra-avengers-basic-1-problem-13',
    title: 'Archimedes’ Last Instructions',
    narrative: [
      'Archimedes bent over his desk, quill scratching furiously across the parchment he had labored over for more than a week.',
      'Before him lay the Stones, their facets catching the candlelight — constant reminders of what was at stake. He knew the net was closing in.',
      'For years the Red Baron’s influence had spread like a shadow, and now his hunger for power had risen to a fever pitch. Only yesterday Archimedes had glimpsed two dark figures lurking beyond his cottage window at dusk, vanishing into the night when he cried out.',
      'With every stroke of the quill he prepared his final instructions, a plan to spirit the Stones away from danger. He might fall, but so long as logic and reason endured, the Order would rise again.'
    ],
    image: '/story/algebraic-avengers/beat_14.png',
    imageAlt: 'Archimedes frantically writes at his oak desk by candlelight, the four glowing Stones before him, shadowy figures faintly visible outside the window.',
    caption: 'Archimedes prepares his final instructions to safeguard the Stones, knowing the Red Baron’s net is closing in.',
  },
  {
    id: 'algebra-avengers-problem-14',
    pathSlug: 'algebra-avengers',
    sequence: 15,
    context: 'problem',
    problemOrder: 14,
    problemId: 'algebra-avengers-basic-1-problem-14',
    title: 'Manfred’s Inheritance',
    narrative: [
      'Manfred Flintz was born into privilege, the son of a powerful family of landowners. His father, Sigfried Flintz, was a domineering, heartless man who cared more for wealth than for kin or community.',
      'Through threats and intimidation, Sigfried bent political decisions in his county to his will. This was the shadow under which Manfred grew up.',
      'At school he strove tirelessly for his father’s approval, hoping that academic success might earn a word of praise. It never came.',
      '“These riddles and arithmetic nonsense serve no purpose,” Sigfried would sneer. “The only things that matter are wealth, power, and control. Something is true because we say it is — that is all the logic we need.”',
      'And so, denied recognition, Manfred turned from his love of study. Year by year, he drifted away from curiosity and reason, until at last he became his father’s mirror — a man shaped by domination, not discovery.'
    ],
    image: '/story/algebraic-avengers/beat_15.png',
    imageAlt: 'A young Manfred Flintz sits at a school desk under the looming shadow of his father Sigfried, who gestures dismissively at books and papers.',
    caption: 'Raised in the shadow of his father’s tyranny, Manfred Flintz slowly abandoned reason and became his father’s mirror.',
  },
  {
    id: 'algebra-avengers-problem-15',
    pathSlug: 'algebra-avengers',
    sequence: 16,
    context: 'problem',
    problemOrder: 15,
    problemId: 'algebra-avengers-basic-1-problem-15',
    title: 'The Riddle of the Stones',
    narrative: [
      'When Reason falters, seek the red,',
      'Three for the road and two for the end.',
      'From the church to the great cathedral,',
      'The mark lies where the ratio bends.',
      '',
      'In waters clear, the blue is bound,',
      'Five parts forward, four remain sound.',
      'The creek that runs from cottage to town,',
      'There the stone of rigor is drowned.',
      '',
      'Climb the steps where learning stays,',
      'Eleven bricks shall mark your way.',
      'Pass six before the yellow gleams,',
      'Where curiosity fuels all dreams.',
      '',
      'Fields of green where farmers sow,',
      'Along the diagonal path you go.',
      'Count seven, then the eighth to last,',
      'There persistence shall hold fast.',
      '',
      'Now guard this riddle, but let none see,',
      'Burn the letter, remember the key.',
      'For paper falls to ash and flame,',
      'Yet truth endures when held in name.'
    ],
    image: '/story/algebraic-avengers/beat_16.png',
    imageAlt: 'An ancient parchment sealed with wax, inscribed with a riddle about the four Stones.',
    caption: 'Archimedes’s letter of instruction telling its recipient hide the Stones within a riddle.',
  },
  {
    id: 'algebra-avengers-beat-17',
    pathSlug: 'algebra-avengers',
    sequence: 17,
    context: 'problem',
    problemOrder: 16,
    problemId: 'algebra-avengers-intermediate-1-problem-1',
    title: 'Father Mersenne Receives the Letter',
    narrative: [
      'Father Marin Mersenne was as much a scientist and mathematician as he was a Catholic priest.',
      'His greatest joy came from unraveling the latest mathematical puzzles, often delivered in the steady stream of letters from his many correspondents.',
      'In fact, Mersenne had become something of a clearinghouse for Europe’s thinkers — linking minds across borders, passing along conjectures, proofs, and problems.',
      'Pierre de Fermat, for example, published little, but wrote often to Mersenne, trusting him to spread ideas through his vast network.',
      '',
      'So when the priest unfolded this strange, cryptic letter from Archimedes, he hesitated.',
      'The words were dense, riddling, and unlike the usual academic queries.',
      'Had the old master finally lost his reason? Mersenne frowned, then shook his head. No… there was intent here.',
      '',
      'He leaned back in his chair, candlelight flickering against the vaulted ceiling above.',
      '"Is this a challenge? A summons? A plea for help?" he murmured.',
      'His eyes lingered on the parchment, thoughts racing.',
      'Whatever it was, Archimedes was stirring something deeper — a call that could not be ignored.'
    ],
    image: '/story/algebraic-avengers/beat_17.png',
    imageAlt: 'Father Marin Mersenne, a 1700s priest and mathematician, sits at his desk by candlelight, holding a cryptic letter with a thoughtful expression.',
    caption: 'Father Mersenne, Europe’s great communicator of ideas, receives Archimedes’s mysterious letter and wonders what it means.',
  },
  {
    "id": "algebra-avengers-beat-18",
    "pathSlug": "algebra-avengers",
    "sequence": 18,
    "context": "problem",
    problemOrder: 17,
    problemId: 'algebra-avengers-intermediate-1-problem-2',
    "title": "The Red Stone",
    "narrative": [
      "Pierre de Fermat sat in his law office, quill idle, the scent of old ink and parchment heavy in the air. Another case, another dispute over land and lineage — the kind of work that dulled the sharp edge of his mind.",
      "His thoughts drifted instead to the strange parcel delivered that morning: a small leather box containing a red stone prism, glinting faintly even in the dim light. Beneath it lay a folded letter, its seal unmarked yet pressed with uncanny precision.",
      "He unfolded it again, eyes tracing the neat, deliberate script:",
      "",
      "'When ratio bends and reason wanes,",
      "Seek the Father where the silence reigns.",
      "The prism guards what words conceal —",
      "Deliver it whole, and thought made real.'",
      "",
      "Fermat frowned, tapping the letter against his palm.",
      "'How singular? A prank from the old friar, perhaps? Or Descartes up to mischief.'",
      "A faint smile tugged at his lips. 'I could do with a break from this tedium anyhow.'",
      "",
      "He closed the leather box, slipped it into his satchel, threw on his heavy coat, and stepped out into the chill of the afternoon — unaware that the quiet corridors of the courthouse would soon feel emptier without him."
    ],
    "image": "/story/algebraic-avengers/beat_18.png",
    "imageAlt": "Pierre de Fermat, 17th-century mathematician and lawyer, sits at his desk surrounded by parchments, gazing thoughtfully at a red stone prism beside an open letter.",
    "caption": "Pierre de Fermat discovers a mysterious red stone and a cryptic verse, setting in motion a journey beyond the bounds of law and reason."
  },
  {
    "id": "algebra-avengers-beat-19",
    "pathSlug": "algebra-avengers",
    "sequence": 19,
    "context": "problem",
    "problemOrder": 18,
    "problemId": "algebra-avengers-intermediate-1-problem-3",
    "title": "The Blue Stone",
    "narrative": [
      "René Descartes was still feeling grumpy at being woken by a knock at the door. He disliked rising early, but the sharp chill of the morning air and the echo of boots in the street told him sleep was now lost for good.",
      "A courier had delivered a small, leather-bound box containing a curious blue stone — smooth, translucent, and faintly humming in the dawn light — along with a folded letter sealed in red wax.",
      "He broke the seal, eyes narrowing as he read the neat, deliberate script:",
      "",
      "'In azure bound where thought takes form,",
      "The line of truth resists the storm.",
      "Seek the priest of measured song,",
      "Where numbers hide and faith grows strong.'",
      "",
      "'Fermat, no doubt,' Descartes grumbled, tossing the page onto the table. 'That vagabond is always trying to test my patience.'",
      "",
      "He paused, staring again at the blue stone, its surface catching the faintest shimmer of candlelight.",
      "'How curious,' he murmured. 'Perhaps not Fermat.'",
      "",
      "He shuffled into the kitchen, cut himself a slice of bread, and leaned on the counter.",
      "His mind — sharp, relentless, and unwilling to rest — began to turn the verse over and over.",
      "The day would not proceed until he had untangled this riddle and the strange purpose of the stone."
    ],
    "image": "/story/algebraic-avengers/beat_19.png",
    "imageAlt": "René Descartes, 17th-century philosopher and mathematician, stands in his Amsterdam doorway as a courier hands him a small leather box containing a glowing blue stone.",
    "caption": "René Descartes receives a mysterious blue stone and a cryptic verse, hinting at a mission involving a 'priest of measured song.'"
  },
  {
    "id": "algebra-avengers-beat-20",
    "pathSlug": "algebra-avengers",
    "sequence": 20,
    "context": "problem",
    "problemOrder": 19,
    "problemId": "algebra-avengers-intermediate-1-problem-4",
    "title": "The Yellow Stone",
    "narrative": [
      "Karl Weierstrass sat thoughtfully in his local tavern, the soft din of conversation and clinking glasses fading into the background. He was getting through his stein of beer more slowly than usual today.",
      "Between sips, his gaze kept drifting toward the small, leather-bound box on the counter before him.",
      "He had opened it earlier that afternoon in his office at the University of Berlin, discovering within a brilliant yellow prism of polished stone — its glow almost alive — and a folded letter written in a careful, looping hand.",
      "He read the verse again, lips moving silently as he traced the words with his finger:",
      "",
      "'Where reason meets the echoed tone,",
      "Find the monk who counts in sound alone.",
      "Give him the light that never dies,",
      "Lest thought grow dim where silence lies.'",
      "",
      "\"What the devil?\" he muttered, eyes fixed on the stone’s shifting hues. \"Whatever can this be for?\"",
      "He raised a hand toward the barkeep. \"Schmidt!\" he called, voice carrying above the din. \"This calls for another stein, I feel.\"",
      "",
      "As the foam settled in his glass once more, Weierstrass stared at the prism’s golden shimmer — unaware that, across centuries, other stones had already begun to move."
    ],
    "image": "/story/algebraic-avengers/beat_20.png",
    "imageAlt": "Karl Weierstrass in a 19th-century Berlin tavern, seated at the bar with a stein of beer, gazing at a small leather-bound box containing a glowing yellow prism.",
    "caption": "Weierstrass studies a mysterious yellow stone and a riddle pointing to a 'monk who counts in sound' — a summons wrapped in code."
  },
  {
    "id": "algebra-avengers-beat-21",
    "pathSlug": "algebra-avengers",
    "sequence": 21,
    "context": "problem",
    "problemOrder": 20,
    "problemId": "algebra-avengers-intermediate-1-problem-5",
    "title": "The Green Stone",
    "narrative": [
      "Marie-Sophie Germain walked briskly along the gravel path toward the Mathematics department. It was Monday—her day to collect the latest set of lecture notes, passed discreetly by a kindly professor who sympathised with her cause. As a woman, she was barred from attending classes or earning a degree, but no decree of men could ever stand in the way of her passion for numbers and truth.",
      "",
      "Today, however, her mind felt curiously unfocused, as though wrapped in fog. She glanced again at the letter she had received that morning, its words looping elegantly in a hand she did not recognise. In her left hand she clutched a small leather box—light, yet oddly warm to the touch.",
      "",
      "Inside the envelope, beneath the salutation, were two short verses written in delicate ink:",
      "",
      "'He dwells where silence cloaks the chime,",
      "A brother bound by code and rhyme.",
      "His prayers are cast in measured tone,",
      "Through numbers sung, his faith is shown.'",
      "",
      "'Where logic’s bounds in silence sleep,",
      "Seek the hall where echoes keep.",
      "Bring the green where numbers chime,",
      "To one who counts the tones of time.'",
      "",
      "She read the lines again, her lips moving unconsciously as though testing their rhythm. “A brother bound by code and rhyme… how strange,” she murmured. Then, half smiling, she slipped the letter back into her coat.",
      "",
      "Her pace quickened, the box secure beneath her arm. Whatever mystery this was, she would not rest until it was solved. After all—was not every great discovery born from a riddle?"
    ],
    "image": "/story/algebraic-avengers/beat_21.png",
    "imageAlt": "Marie-Sophie Germain walking between the limestone buildings of École Polytechnique, holding a small leather box and reading a mysterious letter.",
    "caption": "Sophie Germain deciphers a riddle about a 'brother bound by code and rhyme' — a veiled summons to Father Mersenne, keeper of harmony and number."
  },
  {
    "id": "algebra-avengers-beat-22",
    "pathSlug": "algebra-avengers",
    "sequence": 22,
    "context": "problem",
    "problemOrder": 21,
    "problemId": "algebra-avengers-intermediate-1-problem-6",
    "title": "The Symbol of Circles",
    "narrative": [
      "Carl Friedrich sat at the teacher’s desk, patiently guiding two village children through the geometry problem that had stumped them. The other pupils had already dashed out into the bright field beyond the hall, their laughter echoing through the open windows, but these two lingered—curious, earnest, and unwilling to let the puzzle go unsolved.",
      "",
      "On the slate before them lay half-drawn circles and faint equations, the chalk dusted like snow across Carl’s sleeve.",
      "“The circle,” he explained, tapping the diagram gently, “is a most perfect of shapes. Its mystery lies in how the length around and the space within are bound by the same constant.”",
      "",
      "A sudden knock interrupted the lesson. The door creaked open, and Genevieve—Sir Euler’s junior maid—curtsied in the doorway.",
      "“A letter for you, Squire Gauss. Sir Euler said it should reach you at once.”",
      "",
      "“Thank you, Miss Reeve,” Carl replied with a polite nod, taking the folded parchment and placing it absently upon the desk. His mind was still on the problem before him.",
      "",
      "Turning back to the children, he drew a final symbol on the slate: π.",
      "“This curious mark,” he said with a smile, “ties the circle’s edge to its heart. A strange and powerful thing it is indeed.”",
      "",
      "The two young students gazed at the sign in wonder as Genevieve slipped quietly from the room. The letter lay unopened beside the chalkboard, its wax seal glinting faintly in the afternoon light."
    ],
    "image": "/story/algebraic-avengers/beat_22.png",
    "imageAlt": "Carl Friedrich Gauss sits at the teacher’s desk tutoring two village children in geometry while a sealed letter lies unopened beside him.",
    "caption": "Gauss explains the meaning of π to his young students as an unexpected letter arrives — another summons written in the language of riddles."
  },
  {
    "id": "algebra-avengers-beat-23",
    "pathSlug": "algebra-avengers",
    "sequence": 23,
    "context": "problem",
    "problemOrder": 22,
    "problemId": "algebra-avengers-intermediate-1-problem-7",
    "title": "The Monk Who Counts in Sound",
    "narrative": [
      "“Confounded riddle!” Karl slammed the letter down upon his desk. The verse had haunted him for two days, circling endlessly in his thoughts.",
      "",
      "“The monk who counts in sound alone...” He muttered it again under his breath, scowling. “Utter poppycock. I need some air.”",
      "",
      "Grabbing his coat, he stepped out into the wan afternoon light. For hours he walked — down dusty lanes, across the park, and along the quiet stream that bordered his suburb. The motion cleared the noise in his head, though his mind continued to churn beneath the surface, relentless as a mill wheel.",
      "",
      "Fragments of verse flickered in rhythm with his steps — silence... chime... numbers... tone.",
      "",
      "He paused beside the water, the air thick with the hum of life. Then, from a nearby roof, came the soft cooing of pigeons — hollow, resonant, measured.",
      "",
      "Karl froze. His eyes widened as the pieces locked together.",
      "",
      "“Mersenne!” he cried aloud, startling the birds into flight."
    ],
    "image": "/story/algebraic-avengers/beat_23.png",
    "imageAlt": "Karl Weierstrass walks beside a quiet stream at dusk, pausing as pigeons rise from a rooftop — the moment of realisation dawning in his eyes.",
    "caption": "Weierstrass wanders in thought until the measured coo of pigeons reveals the answer hidden in the riddle — the monk who counts in sound: Father Mersenne."
  },
  {
    "id": "algebra-avengers-beat-24",
    "pathSlug": "algebra-avengers",
    "sequence": 24,
    "context": "problem",
    "problemOrder": 23,
    "problemId": "algebra-avengers-intermediate-1-problem-8",
    "title": "The Priest of Measured Song",
    "narrative": [
      "For the next week, René Descartes rose at noon each day, as was his habit since childhood. The long mornings in bed, once prescribed for his frail health, had become the crucible of his thought. It was in those quiet hours, with the world still distant, that his ideas would roll and settle, forming unseen connections.",
      "",
      "“Seek the priest of measured song... seek the priest of measured song...” The phrase had been turning over in his mind for days now, though he scarcely noticed it.",
      "",
      "He dressed slowly, still half lost in reflection. His mind wandered between the rhythms of mathematics and the forms of space — how lines and planes might be tamed by number. Analytic geometry, he mused. If only others could see where this might lead.",
      "",
      "Stepping out into the lane, he adjusted his cloak and continued, muttering to himself.",
      "“I must put these thoughts into words... there’s great power here. I’ll write to Mersenne and ask his counsel.”",
      "",
      "He stopped mid-stride, smiling as the realization dawned.",
      "",
      "“Mersenne!” he laughed softly. “Goodness me... it was obvious all along.”"
    ],
    "image": "/story/algebraic-avengers/beat_24.png",
    "imageAlt": "René Descartes walks through a quiet village lane beneath the midday sun, lost in thought, a knowing smile forming as inspiration strikes.",
    "caption": "Descartes reflects on the harmony between numbers and geometry, realising that the 'priest of measured song' in his thoughts was none other than Father Mersenne."
  },
  {
    "id": "algebra-avengers-beat-25",
    "pathSlug": "algebra-avengers",
    "sequence": 25,
    "context": "problem",
    "problemOrder": 24,
    "problemId": "algebra-avengers-intermediate-1-problem-9",
    "title": "A Beautiful Little Proof",
    "narrative": [
      "“Ha! What a beautiful little proof,” thought Pierre de Fermat, setting down his quill. “I never would have dreamed of such simplicity. Mathematics never ceases to amaze.”",
      "",
      "He leaned back in his chair, letting the tension ease from his shoulders. His mind, bound tight around the theorem for hours, began at last to unfurl. The midday sun had long passed; his untouched lunch sat cooling by the window.",
      "",
      "He gazed up at the timbered ceiling, a faint draught stirring the edges of the parchment before him. For a few blissful moments, he allowed himself to think of nothing at all.",
      "",
      "Then, with a quiet sigh, he murmured, “I really ought to see to that matter of the farm lease — poor old Boucher needs someone in his corner.” A gentle smile crossed his face. “And I suppose I’d best see that stone delivered to old Mersenne, as requested.”"
    ],
    "image": "/story/algebraic-avengers/beat_25.png",
    "imageAlt": "Pierre de Fermat sits at his writing desk, quill set aside, sunlight slanting across scattered parchments as a faint breeze moves through the open window.",
    "caption": "After discovering a simple and elegant proof, Fermat pauses to rest — unaware that his next errand, a delivery to Father Mersenne, will soon draw him deeper into the mystery."
  },
  {
    "id": "algebra-avengers-beat-26",
    "pathSlug": "algebra-avengers",
    "sequence": 26,
    "context": "problem",
    "problemOrder": 25,
    "problemId": "algebra-avengers-intermediate-1-problem-10",
    "title": "The Brother of Measured Song",
    "narrative": [
      "“This must be a test,” thought Sophie, staring once again at the strange letter. She had read and reread it throughout the day, but its meaning refused to reveal itself.",
      "",
      "“Ah, Monsieur Le Blanc!” came a familiar voice. Joseph-Louis Lagrange stood at the entrance to the library, smiling as he noticed Sophie seated at a long oak desk surrounded by open books. “Working hard as always, I see.”",
      "",
      "Sophie looked up, a spark of amusement in her eyes. “Monsieur Lagrange!” she said warmly. “Yes — though not on mathematics, I’m afraid. I received this curious letter yesterday and haven’t the faintest idea what to make of it.”",
      "",
      "She passed the parchment across the desk. Lagrange adjusted his spectacles and began to read aloud, his voice echoing softly through the quiet hall:",
      "",
      "‘He dwells where silence cloaks the chime,",
      "A brother bound by code and rhyme.",
      "His prayers are cast in measured tone,",
      "Through numbers sung, his faith is shown.’",
      "",
      "‘Where logic’s bounds in silence sleep,",
      "Seek the hall where echoes keep.",
      "Bring the green where numbers chime,",
      "To one who counts the tones of time.’",
      "",
      "When he finished, Lagrange studied the page for a long moment, tapping a finger against the verse. “A brother bound by code and rhyme… That, Mademoiselle Germain, can mean only one man.”",
      "",
      "Sophie leaned forward. “Who, Monsieur?”",
      "",
      "“Father Marin Mersenne,” he said at last, a smile flickering beneath his white-grey beard. “Franciscan monk, philosopher, and the keenest ear in all of mathematics. He made a life’s study of harmony — of sound itself, how strings and numbers speak the same language. If this letter speaks of measured song and numbers that chime, it points unmistakably to him.”",
      "",
      "Sophie sat back, eyes wide with realization. “The Brother of measured song…” she whispered. “Mersenne.”"
    ],
    "image": "/story/algebraic-avengers/beat_26.png",
    "imageAlt": "Sophie Germain and Joseph-Louis Lagrange seated at a long oak library table, the letter between them as Lagrange reads aloud under the soft glow of afternoon light.",
    "caption": "Lagrange helps Sophie decipher the riddle, revealing that the mysterious 'Brother bound by code and rhyme' is Father Mersenne — the monk who united mathematics and sound."
  },
  {
    "id": "algebra-avengers-beat-27",
    "pathSlug": "algebra-avengers",
    "sequence": 27,
    "context": "problem",
    "problemOrder": 26,
    "problemId": "algebra-avengers-intermediate-1-problem-11",
    "title": "The Shadows of the Order",
    "narrative": [
      "There was a chill in the air as Carl Friedrich walked down the lane toward the stables, rubbing his hands together to warm his fingertips. “A day well spent,” he thought cheerfully. He always loved teaching mathematics — especially to children, whose curiosity reminded him of his own beginnings.",
      "",
      "He plunged his hands into his coat pockets as the cold deepened. His fingers brushed against a folded parchment. “What’s this?” he murmured, pulling it free. Then he remembered — the letter he’d tucked away that afternoon.",
      "",
      "He broke the seal, the wax cracking softly in the dim light, and unfolded the paper. In a beautiful, looping hand it read:",
      "",
      "We have known from long ago,",
      "That soon enough your skill would show.",
      "And now the shadows of fear close in,",
      "And power falls to those who sin.",
      "",
      "Soon you’ll hear from learned masters,",
      "And change the course of what comes after.",
      "Listen well to all they teach,",
      "And hold the Order against the breach.",
      "",
      "Carl shivered — not only from the cold, but from a sudden, creeping unease. He glanced around the empty lane, its cobblestones silvered by twilight.",
      "",
      "“What is this? The Order?”",
      "",
      "He quickened his pace, heart pounding as the wind rustled through the bare trees. By the time he reached the stables, he was almost running, desperate for the safety of light and company."
    ],
    "image": "/story/algebraic-avengers/beat_27.png",
    "imageAlt": "Carl Friedrich Gauss walks briskly through a darkening village lane, clutching a parchment as the last light fades into shadow.",
    "caption": "Gauss receives a cryptic letter warning of 'The Order' — a secret force rising against reason — and feels the first chill of fear as the shadows close in."
  },
  {
    "id": "algebra-avengers-beat-28",
    "pathSlug": "algebra-avengers",
    "sequence": 28,
    "context": "problem",
    "problemOrder": 27,
    "problemId": "algebra-avengers-intermediate-1-problem-12",
    "title": "The Call of the Keepers",
    "narrative": [
      "The sun hung low over Syracuse, bleeding gold across the marble walls. Within his study, Archimedes bent over a small chest of carved cedar. The room was silent save for the scratch of his quill and the faint hum of the sea beyond the walls. He paused, the tremor in his hand betraying the weight of his years.",
      "",
      "He knew the end was near. The Romans had breached the gates; the shouts of soldiers echoed faintly through the streets. Yet his mind remained still — sharp as ever.",
      "",
      "On the table before him lay four stones, each cut to a perfect geometric form: a red triangle, a blue cube, a green pentagon, and a yellow hexagon. Symbols of reason, proof, harmony, and discovery — the four pillars of mathematics.",
      "",
      "He dipped his quill once more and began to write in hurried, deliberate strokes:",
      "",
      "When shadow veils the scholar’s flame,",
      "And truth is bent by fear and fame,",
      "Four minds shall rise, though ages torn,",
      "By proof and stone, the world reborn.",
      "",
      "Seek those who reason through the storm,",
      "Whose hearts by logic’s fire are warm.",
      "Guard well the code, the circle’s end,",
      "Till order mends what none defend.",
      "",
      "He sealed the parchment and pressed it against the chest of stones. “Reason and logic will come under siege,” he murmured, almost to himself. “And when they do… they must find you.”",
      "",
      "Outside, the sound of iron clashed with shouts and flame. Archimedes closed the lid, whispering the final words of his theorem — and with that, set in motion a plan that would echo through centuries.",
      "",
      "Across time, unseen, four minds would one day stir — the keepers of the stones, summoned by his verse."
    ],
    "image": "/story/algebraic-avengers/beat_28.png",
    "imageAlt": "Archimedes in his study at Syracuse, golden light illuminating a cedar chest containing four glowing geometric stones as distant flames rise outside the walls.",
    "caption": "As Syracuse falls, Archimedes enacts an ancient plan — sealing away four sacred stones and inscribing a verse that will summon their keepers across the centuries."
  },    
  {
    "id": "algebra-avengers-beat-29",
    "pathSlug": "algebra-avengers",
    "sequence": 29,
    "context": "problem",
    "problemOrder": 28,
    "problemId": "algebra-avengers-intermediate-1-problem-13",
    "title": "The Call of Logic",
    "narrative": [
      "Euclid walked the dusty path home from the Library of Alexandria, the amber light of dusk softening the great city’s marble domes. Book V of The Elements was nearing completion, and a quiet pride swelled within him. Years of toil, of endless proof and patient refinement, had at last begun to form a complete harmony — a geometry of thought as pure as the heavens themselves.",
      "",
      "As he walked, a faint sound reached him on the wind — distant at first, like the echo of a song carried from the sea. He slowed his pace, listening. The sound grew clearer, its rhythm strangely measured, like the cadence of verse whispered through the ages.",
      "",
      "Then he heard the words distinctly — a voice not of this world, yet familiar in its perfect balance of reason and music:",
      "",
      "‘O you of logic and reason pure,",
      "Are called upon to so endure,",
      "The cuts and lashes of another age,",
      "Where irrationality meets its final stage.’",
      "",
      "‘I call you now with this fair stone,",
      "To venture long and far from home,",
      "Across the waves, across the years,",
      "For you alone allay my fears.’",
      "",
      "Euclid stopped where he stood, the air trembling with meaning. He looked toward the horizon, where the last light of day touched the waves, and felt a quiet certainty settle over him.",
      "",
      "He did not question the voice. Logic had always guided him — and now, reason itself had called.",
      "",
      "He would answer."
    ],
    "image": "/story/algebraic-avengers/beat_29.png",
    "imageAlt": "Euclid walks the dusty road from the Library of Alexandria at sunset, scrolls under one arm, as faint ethereal words echo on the wind.",
    "caption": "As twilight falls over Alexandria, Euclid hears the ancient call — a verse summoning him as the first Keeper of the Stones, guardian of reason and logic."
  },
  {
    "id": "algebra-avengers-beat-30",
    "pathSlug": "algebra-avengers",
    "sequence": 30,
    "context": "problem",
    "problemOrder": 29,
    "problemId": "algebra-avengers-intermediate-1-problem-14",
    "title": "The Keeper of the Heavens",
    "narrative": [
      "Eudoxus of Cnidus sat wearily on the stone steps leading up to his observatory. The night had been long and cold, the stars fading now into the pale wash of dawn. He had spent the hours tracing the celestial spheres, refining his planetary models — another small attempt to understand the order of the heavens.",
      "",
      "He exhaled slowly, feeling the ache of sleeplessness settle behind his eyes. The gentle hum of morning insects mingled with the rhythm of the waves far below. For a moment, his thoughts drifted toward the eternal — the harmony that must bind all motion, from the turning of the Earth to the paths of the wandering stars.",
      "",
      "His head nodded, then snapped upright. A faint rhythm seemed to echo from his dreams into waking. It pulsed softly at first, like the measured beat of a pendulum. Then words began to form within it — distant yet clear, resonant as if spoken by the heavens themselves:",
      "",
      "“Through stars and spheres thy reason flies,",
      "To chart the truth that darkness hides;",
      "From circle’s law to measured flame,",
      "Guard thought from those who’d mar its name.”",
      "",
      "“When shadow clouds the scholar’s art,",
      "Let logic’s compass guide thy heart;",
      "Rise, Eudoxus — keeper bright,",
      "To stand for reason, flame, and light.”",
      "",
      "The final word lingered in the air long after the sound had faded. Eudoxus sat motionless, his heart thudding softly beneath his robes. He looked up at the paling sky, where the last star flickered out like a signal answered.",
      "",
      "He understood now. He had been called — not merely as a mathematician, but as a Keeper of the Stones.",
      "",
      "The defense of reason had begun."
    ],
    "image": "/story/algebraic-avengers/beat_30.png",
    "imageAlt": "Eudoxus sits on the observatory steps at dawn, eyes lifting to a fading sky as ethereal words seem to shimmer in the air.",
    "caption": "At the edge of night and day, Eudoxus hears a celestial summons — a verse naming him Keeper of the Stones and defender of reason."
  },
  {
    "id": "algebra-avengers-beat-31",
    "pathSlug": "algebra-avengers",
    "sequence": 31,
    "context": "problem",
    "problemOrder": 30,
    "problemId": "algebra-avengers-intermediate-1-problem-15",
    "title": "The Keeper of the Curve",
    "narrative": [
      "Apollonius of Perga scratched out conic sections on his parchment. His concentration was unbreakable — his mind like a relentless machine, pressing statements back to first principles.",
      "",
      "“Where is the link?” he murmured. “One devolves to the other… parabola to ellipse… ellipse to circle…”",
      "",
      "A cool breeze tugged at his sleeve though it had been a hot, still day. He looked up. Then, without warning, something inside him shifted — as though the axis of thought itself had tilted — and he heard a faint, harmonious humming resolve into words:",
      "",
      "“O master of the curve and line,",
      "Who bent the cone to truth’s design,",
      "Whose hand revealed in ordered grace",
      "The hidden laws of shape and space;”",
      "",
      "“Arise, Apollonius — stand once more,",
      "As reason buckles under war;",
      "Guard what the ages learned and own,",
      "Keeper of thought, and shield of stone.”",
      "",
      "The sound faded like mist burned from sunlight. Apollonius stared at the still air, breathing deeply.",
      "",
      "“And so the day comes,” he said aloud — though no one stood there to hear him.",
      "",
      "He set down his quill with calm resolve. He was ready."
    ],
    "image": "/story/algebraic-avengers/beat_31.png",
    "imageAlt": "Apollonius seated at his writing table over parchment of conic sections as an unseen voice seems to echo in the still air.",
    "caption": "A verse calls Apollonius of Perga to rise as a Keeper of the Stones — guardian of reason drawn from curves, cones, and pure deduction."
  },
  {
    "id": "algebra-avengers-beat-32",
    "pathSlug": "algebra-avengers",
    "sequence": 32,
    "context": "problem",
    "problemOrder": 31,
    "problemId": "algebra-avengers-advanced-1-problem-1",
    "title": "The Final Keeper",
    "narrative": [
      "Diophantus of Alexandria sat among the colonnades of the Great Library, the polished marble cool beneath his hands. Before him lay a worn copy of his own Arithmetica, its margins crowded with trials of unknowns and half-finished equations.",
      "",
      "He leaned in closer, lips moving silently as he traced a problem whose structure still pleased him after years of toil. The hush of the vast hall was complete — until, without warning, a cool breeze slipped between the shelves and ruffled the parchment beneath his fingers.",
      "",
      "He looked up sharply. The air wavered — not with sound, but with something like meaning — and then a voice emerged, steady as a proof recited from memory:",
      "",
      "“Through unknowns bound in ciphered art,",
      "You tamed the sums that rend apart;",
      "Where numbers wrestle without end,",
      "You made the rational their friend.”",
      "",
      "“Rise, Diophantus — answer now,",
      "As doubt would break what minds allow;",
      "Guard thought where proof and order stand,",
      "Last Keeper called to stay the hand.”",
      "",
      "The final consonant faded into the cavernous dome of the library. Diophantus remained still — not fearful, but sharpened, like iron struck to edge.",
      "",
      "He closed the book with deliberate care. “So the mantle falls to me,” he said softly, as if naming a theorem at last complete.",
      "",
      "The last of the four Keepers had risen."
    ],
    "image": "/story/algebraic-avengers/beat_32.png",
    "imageAlt": "Diophantus seated among towering shelves in the Great Library of Alexandria as a sudden breeze stirs the parchment of Arithmetica before him.",
    "caption": "In the silence of the Great Library, Diophantus receives the final summons — called to rise as the last Keeper of the Stones and defender of reason."
  },
  {
    "id": "algebra-avengers-beat-33",
    "pathSlug": "algebra-avengers",
    "sequence": 33,
    "context": "problem",
    "problemOrder": 32,
    "problemId": "algebra-avengers-advanced-1-problem-2",
    "title": "Carl and Emmy exchange parchments",
    "narrative": [
      "Carl’s heart was still racing as he shut the stable door behind him. He scarcely noticed the sting in his frozen fingertips — the letter he carried had driven all other sensation from his mind.",
      "",
      "A sudden, heavy rap at the door made him jump. His pulse spiked.",
      "“Who is it?” he shouted before he could stop himself, all courtesy gone.",
      "",
      "“It is Emmy, Squire Gauss,” came the reply. “Forgive the lateness — I needed to bring you this at once.”",
      "",
      "Carl opened the door and bowed low. “It is I who must beg forgiveness, Your Highness. My manner was —”",
      "",
      "Emmy cut him off gently. “Think nothing of it.” She studied his face. His colour was high; fear sat behind his eyes. “Are you unwell, Squire Gauss?”",
      "",
      "He said nothing. Instead he held out the letter with a trembling hand. She took it and read quickly, her brow tightening. Then she reached into the small volume she carried and drew out a slip of parchment that had fallen loose.",
      "",
      "Without a word, she placed it in Carl’s palm.",
      "",
      "For a long moment they stood together in the cold, the only motion their breath turning to grey smoke in the air — two minds held still by the same unsettling summons."
    ],
    "image": "/story/algebraic-avengers/beat_33.png",
    "imageAlt": "Carl Gauss and Princess Emmy standing in the cold stable entry, exchanging letters with visible tension in the winter air.",
    "caption": "A late-night deliverance binds Gauss and Emmy into the unfolding mystery — the summons has reached them both."
  },
  {
    "id": "algebra-avengers-beat-34",
    "pathSlug": "algebra-avengers",
    "sequence": 34,
    "context": "problem",
    "problemOrder": 33,
    "problemId": "algebra-avengers-advanced-1-problem-3",
    "title": "The Four As One",
    "narrative": [
      "“Welcome, travellers!” beamed Father Mersenne, opening the small wooden door to his cottage. Before him stood four of the greatest minds in the history of reason. “Come in, come in,” he waved, almost giddy. “What an honour — four in one life! Sit, sit — I will bring bread.”",
      "",
      "He hurried to the kitchen, speaking the whole way, and returned with a loaf, a knife, and four cups. He set them down with hands still trembling.",
      "",
      "“It is a rare honour indeed to see the four Keepers as one. A message came with you — let me read it aloud.”",
      "",
      "He reached behind a stack of manuscripts and took up a sheet of parchment. Archimedes’ ancient hand declared:",
      "",
      "“And so assemble minds of four,",
      "In time ahead and time before;",
      "Across the nations you must go,",
      "To loosen chains that none yet know.”",
      "",
      "“For power now is blind and cold,",
      "And grasps men’s lives with thoughtless hold;",
      "Where reason sleeps and rights decay,",
      "Your teaching lights the narrow way.”",
      "",
      "Mersenne lowered the page slowly. The calm, steady faces before him filled him with awe — the quiet presence of minds that could move worlds.",
      "",
      "“We are ready, Father,” said Euclid, finishing the last piece of bread."
    ],
    "image": "/story/algebraic-avengers/beat_34.png",
    "imageAlt": "Father Mersenne welcoming four ancient mathematicians into his candlelit cottage, parchment in hand and bread set on the table.",
    "caption": "In a humble cottage, the four Keepers assemble at last — Archimedes' charge read aloud, and their task set before them."
  },
  {
    "id": "algebra-avengers-beat-35",
    "pathSlug": "algebra-avengers",
    "sequence": 35,
    "context": "problem",
    "problemOrder": 34,
    "problemId": "algebra-avengers-advanced-1-problem-4",
    "title": "The Red Baron Moves",
    "narrative": [
      "Even the crows seemed to sense the danger as the Red Baron scratched angrily across his pad. His lead henchman had just reported that no trace of the stones had been found. A cold wind tore down the hill from BlackHouse, making the scene feel darker still. There was no telling what would happen next.",
      "",
      "The henchman stood rigid, throat locked by an interminable silence. He did not dare swallow, did not dare breathe.",
      "",
      "At last the scratching stopped. The Baron set down his pen with surgical precision. Then, without looking up, he spoke — the words more chilling than a shout:",
      "",
      "“Bring me Riemann,” he snarled."
    ],
    "image": "/story/algebraic-avengers/beat_35.png",
    "imageAlt": "A stern Red Baron seated at a desk under dim light, quill paused mid-scratch as his terrified henchman stands before him.",
    "caption": "The Red Baron learns the stones remain hidden — and with rising fury, he orders the next move: summon Riemann."
  },
  {
    "id": "algebra-avengers-beat-36",
    "pathSlug": "algebra-avengers",
    "sequence": 36,
    "context": "problem",
    "problemOrder": 35,
    "problemId": "algebra-avengers-advanced-1-problem-5",
    "title": "Summoned",
    "narrative": [
      "Bernhard Riemann could feel the tension in the guards long before he saw the door. He had been summoned before the Red Baron many times, but never in such a silence, never with such tightly clenched jaws and eyes fixed to the floor.",
      "",
      "He had served as the Baron’s mathematician for several years, ever since his father’s farm had been seized and there was no other way to keep his family from ruin. He was a man of fierce intellect and inward habits — quiet enough to be forgotten in a room, yet sharp enough to see through every lie and motive that passed before him.",
      "",
      "He had seen the greed. He had seen the chaos gather like a storm behind the velvet curtains of power. And now, as he walked between two trembling guards toward the Baron’s chamber, he understood: something had shifted. The search for the stones had reached a breaking point — and the Baron was about to cross a line that could not be uncrossed.",
      "",
      "Riemann squared his shoulders. Whatever happened next, he would face it with open eyes."
    ],
    "image": "/story/algebraic-avengers/beat_36.png",
    "imageAlt": "Bernhard Riemann escorted down a dim corridor by tense guards toward a heavy wooden door.",
    "caption": "Sensing a change in the air, Riemann is summoned to the Red Baron's chamber as the hunt for the stones reaches a perilous turning point."
  },
  {
    "id": "algebra-avengers-beat-37",
    "pathSlug": "algebra-avengers",
    "sequence": 37,
    "context": "problem",
    "problemOrder": 36,
    "problemId": "algebra-avengers-advanced-1-problem-6",
    "title": "A genius leveraged",
    "narrative": [
      "Bernhard Riemann stood in the vast dining hall, torchlight pooling beneath BlackHouse’s arched vaults while the Red Baron paced between the long tables like a caged predator. His voice cracked through the air — demanding, furious — insisting that Riemann reveal how the Order shields the Stones’ power.",
      "",
      "Riemann’s breath caught. The threats against his father gnawed at his resolve. With his throat tight and pulse hammering in his ears, he began to speak.",
      "",
      "He recounted the legend of the four ancient Keepers:",
      "Eudoxus mapping the heavens,",
      "Apollonius guarding the curves,",
      "Euclid binding the axioms,",
      "Diophantus taming the unknowns —",
      "and how Archimedes had entrusted each with a shard of reason that only the righteous could reunite.",
      "",
      "A goblet slammed against wood. Wine leapt. Riemann flinched. The Baron’s eyes burned.",
      "",
      "So Riemann continued — he spoke of the second line, those foreseen to awaken what the first line had sealed:",
      "Fermat, guardian of elegant proof,",
      "Descartes, forger of the analytic plane,",
      "Germain, defier of silence and exclusion,",
      "Weierstrass, sculptor of rigor from chaos.",
      "",
      "Archimedes, he explained, had veiled the Stones with riddles that only a harmony of past and present minds could unlock — and once aligned, their power could either restore the Order… or unmake it entirely.",
      "",
      "At that, the Baron lunged. He seized Riemann by the collar, face close and trembling with greed.",
      "“Then I will forge that harmony myself,” he hissed, “even if I must set them against each other to do it.”",
      "",
      "Riemann lowered his gaze — not in surrender, but to hide the spark of defiance still alive behind his fear."
    ],
    "image": "/story/algebraic-avengers/beat_37.png",
    "imageAlt": "Riemann standing in a torchlit hall as the Red Baron seizes him by the collar across a long banquet table.",
    "caption": "Pressed by threat and fury, Riemann reveals the prophecy of the two lines of Keepers — and the Baron vows to twist it to his own will."
  },
  {
    "id": "algebra-avengers-beat-38",
    "pathSlug": "algebra-avengers",
    "sequence": 38,
    "context": "problem",
    "problemOrder": 37,
    "problemId": "algebra-avengers-advanced-1-problem-7",
    "title": "Angst into Resolve",
    "narrative": [
      "Riemann staggered into the corridor, his breath ragged and his pulse pounding in his temples. The echo of the Baron’s words still rang in his ears like iron striking stone. His mind reeled — visions of his father’s farm, of the Order, of the Stones’ terrible promise — all crashing together in a blur of guilt and dread.",
      "",
      "He pressed a trembling hand to the wall for balance. “What have I done?” he whispered. The question cut deeper each time it escaped his lips.",
      "",
      "Tears blurred his vision. He had revealed too much — perhaps everything — yet he could not undo what was spoken. The air in the hallway felt heavy, charged with consequence.",
      "",
      "And then, beneath the crushing weight of fear, something shifted. A spark — the same one that had driven him to seek truth in infinite spaces — flared within. His breathing slowed. The chaos in his mind began to settle into focus.",
      "",
      "He straightened. His jaw tightened. “I must warn them,” he said quietly, resolve hardening like steel in his chest.",
      "",
      "Without another glance behind, Riemann vanished into the dark."
    ],
    "image": "/story/algebraic-avengers/beat_38.png",
    "imageAlt": "Riemann rushing down a dimly lit stone corridor, cloak billowing as torches flicker against the walls.",
    "caption": "Haunted by what he’s revealed, Riemann resolves to act — to warn the others before the Baron unleashes the Stones’ power."
  },
  {
    "id": "algebra-avengers-beat-39",
    "pathSlug": "algebra-avengers",
    "sequence": 39,
    "context": "problem",
    "problemOrder": 38,
    "problemId": "algebra-avengers-advanced-1-problem-8",
    "title": "The Harmonic Convergence",
    "narrative": [
      "Riemann sat in silence, his eyes lowered, while the Red Baron’s sneer carved through the air.",
      "“I’ll have the Stones soon enough,” the Baron hissed. “I have eyes everywhere. And once I do, you will fuse all their power into one.”",
      "",
      "His laugh — harsh and hollow — ricocheted off the stone walls of Riemann’s study. With a thud, he hurled several sheets of parchment onto the desk.",
      "“Sketch what is required,” he growled. “And be swift. I think your father would… agree.”",
      "",
      "The door slammed behind him, leaving only the echo of his boots and the pounding of Riemann’s heart.",
      "",
      "He sat frozen for a long moment. Then, without a word, he reached for his quill. Through the night he worked, summoning text after text from the library, scouring through pages of geometry, analysis, and number theory. Fragments of memory stirred — forgotten theorems, faint whispers of symmetry and flow — until, piece by piece, a pattern began to take shape.",
      "",
      "When the first light of dawn crept across his desk, the parchment was no longer empty. Lines of symbols curved and intertwined, equations unfolding like constellations.",
      "",
      "Riemann stepped back, exhausted. He knew what he had written — a lattice of perfect balance, a map of resonance between all things.",
      "",
      "The Harmonic Convergence had been born."
    ],
    "image": "/story/algebraic-avengers/beat_39.png",
    "imageAlt": "Bernhard Riemann surrounded by books and parchment, illuminated by dawn light as intricate equations fill the desk before him.",
    "caption": "Under threat and through the night, Riemann completes his creation — the Harmonic Convergence, a design capable of uniting the Stones’ power."
  },
  {
    "id": "algebra-avengers-beat-40",
    "pathSlug": "algebra-avengers",
    "sequence": 40,
    "context": "problem",
    "problemOrder": 39,
    "problemId": "algebra-avengers-advanced-1-problem-9",
    "title": "The Posters of Schmald",
    "narrative": [
      "Morning light spilled unevenly across the cobblestones of Schmald. A small crowd had gathered outside the baker’s shop, voices low and uncertain. The night before, the walls of the village had been bare. Now they were plastered with the same strange notice — printed in bold, urgent letters:",
      "",
      "WANTED",
      "Four strangers to this village — likely dressed in foreign garb.",
      "They may appear civil. Do not approach.",
      "Report all sightings to your local Sheriff of the Red immediately.",
      "The safety of all is at stake.",
      "",
      "Per Müller, the baker, squinted at the poster as he wiped flour from his hands. “What do you make of this, Gertrude?” he asked his wife, who stood beside him with a basket of rolls.",
      "",
      "“Not a clue, Per,” she murmured, frowning. “Though it sounds serious enough.”",
      "",
      "A hush fell over the street. The couple exchanged a wary glance as a tall man in a red cloak strode past, his boots echoing sharply on the stone. Without another word, they slipped back into the shop just as the service bell rang, its chime breaking the uneasy silence that had settled over the village."
    ],
    "image": "/story/algebraic-avengers/beat_40.png",
    "imageAlt": "Villagers gathered on a cobblestone street, staring at fresh Red Order posters on the walls under the pale morning light.",
    "caption": "As dawn breaks over Schmald, strange posters appear overnight — warnings of four mysterious strangers and the reach of the Red Order grows."
  },
  {
    "id": "algebra-avengers-beat-41",
    "pathSlug": "algebra-avengers",
    "sequence": 41,
    "context": "problem",
    "problemOrder": 40,
    "problemId": "algebra-avengers-advanced-1-problem-10",
    "title": "The Message in Harmony",
    "narrative": [
      "Riemann worked quickly but with precision, each symbol drawn in careful silence. When he finished, he wrapped the parchment and slate together into what would appear — to any casual reader — as a treatise on spectral acoustics, filled with dense harmonic analysis and notes on wave interference. But woven into the margins, invisible to all but Mersenne’s network, were tiny markings — prime-number bar-lines — an encrypted rhythm only one man alive would understand.",
      "",
      "At dawn, Riemann sealed the packet and pressed it into the hands of a travelling violinist bound for Paris. “Deliver this to the Brother of Measured Song,” he whispered. Then, leaning close, he added the cipher’s key: “Critical line.”",
      "",
      "Days later, Father Mersenne received the parcel in his modest study. The moment he saw the rhythmic spacing between the numbers, he knew its source. Without delay he summoned the four ancient Keepers — Euclid, Apollonius, Diophantus, and Eudoxus — who gathered around his resonant oak table as he unrolled the parchment.",
      "",
      "They placed their palms upon the edges and began to hum in harmony. The table itself seemed to respond — the lines on the page shimmered, arcs tightening into symbols that glowed faintly in the candlelight.",
      "",
      "The code revealed its hidden message:",
      "",
      "“When reason’s voice is bound by chains,",
      "And power stalks through darkened veins,",
      "Beware the hand that mirrors friend,",
      "For false accord will mark the end.”",
      "",
      "“He seeks the Stones, yet knows not where,",
      "He breathes deceit into the air;",
      "The four are known, their paths entwined,",
      "But shadow walks not far behind.”",
      "",
      "Mersenne exhaled slowly. “So the breach begins,” he murmured. The four mathematicians exchanged solemn glances. The warning had arrived — and war for the soul of reason was no longer a distant threat."
    ],
    "image": "/story/algebraic-avengers/beat_41.png",
    "imageAlt": "Father Mersenne and the four ancient Keepers gathered around a candlelit oak table as glowing symbols emerge on Riemann’s parchment.",
    "caption": "Riemann’s coded treatise reaches Mersenne, who deciphers its warning with the four Keepers — the Red Baron knows of the Stones, and reason itself stands at the brink."
  },
  {
    "id": "algebra-avengers-beat-42",
    "pathSlug": "algebra-avengers",
    "sequence": 42,
    "context": "problem",
    "problemOrder": 41,
    "problemId": "algebra-avengers-advanced-1-problem-11",
    "title": "The Prime Pulse",
    "narrative": [
      "Pierre de Fermat’s back ached as the coach finally rattled onto the outer streets of Paris. For nine long days he had endured the jolts and sways of the journey from Toulouse — the wooden wheels hammering each cobblestone like an accusation.",
      "",
      "“Infernal contraptions,” he muttered, pressing a hand to the small of his back. Yet despite the fatigue, a grin crept across his face. “How many years has it been now?” he thought. “Too many since I last saw dear Mersenne.”",
      "",
      "Then he felt it — a faint, rhythmic tremor from his coat pocket. He frowned and drew out the small red stone, its polished surface pulsing with soft, even flashes. At first the rhythm seemed random, like the crackle of distant thunder. But as he listened closer, a pattern began to form — two beats, then three beats, then five beats, then seven beats — the unmistakable cadence of the prime numbers.",
      "",
      "His brow furrowed. “Two, three, five, seven…” he whispered, his mind whirring. Then a pause, and the sequence began anew — this time reversed. “Seven, five, three, two…”",
      "",
      "A realization chilled him: the primes were collapsing inward, a signal of convergence. He reached for his notebook and scribbled a quick calculation — ratios of intervals matching the harmonic frequencies of a vibrating string. The values aligned perfectly with a descending series he had once discussed in a letter to Mersenne.",
      "",
      "“This isn’t chance,” he breathed. “It’s a warning.”",
      "",
      "The pattern pulsed again, brighter now — a silent message in number and rhythm, calling him toward the Brother of Measured Song."
    ],
    "image": "/story/algebraic-avengers/beat_42.png",
    "imageAlt": "Pierre de Fermat seated in a dim carriage entering Paris, the red stone glowing in his hand as rhythmic pulses reflect in his thoughtful eyes.",
    "caption": "On his long journey to Paris, Fermat feels the red stone awaken — its pulse beating out the prime sequence, a mathematical warning meant for him alone."
  },
  {
    "id": "algebra-avengers-beat-43",
    "pathSlug": "algebra-avengers",
    "sequence": 43,
    "context": "problem",
    "problemOrder": 42,
    "problemId": "algebra-avengers-advanced-1-problem-12",
    "title": "The False Accord",
    "narrative": [
      "Evening settled over Paris like a held breath. Inside the cloister of the Minimes, Father Mersenne’s study glowed with candlelight, the parchment from Riemann still spread across the great oak table. The four ancient Keepers — Euclid, Apollonius, Diophantus, and Eudoxus — stood nearby, their faces calm but their minds alight with unease.",
      "",
      "“The warning was clear,” murmured Mersenne. “A false accord is near. The Red Order is already listening.”",
      "",
      "He moved to the arched corridor where younger friars adjusted tuning forks and signal mirrors, their faint metallic chime weaving a fragile network through the air. The harmonic web shimmered — an unseen barrier of sound meant to reveal any resonance from the Stones.",
      "",
      "Then came it: a tone, half a beat too pure. To most ears it would have sounded harmonious — but to Mersenne, it was the sound of deception.",
      "",
      "He turned. A figure in a brown habit approached, moving with practiced calm. The monk’s voice joined the others in chant, echoing Mersenne’s pitch exactly. Too exactly.",
      "",
      "Mersenne’s pulse quickened. “Brother Alain?” he asked, testing. The man smiled, serene. And then Mersenne heard it — a missing prime interval, the same flaw Riemann had foreseen.",
      "",
      "He stepped back toward the great organ. Behind him, the four Keepers tightened their stance. “The Red Order is here,” Euclid whispered.",
      "",
      "Mersenne hesitated. To break cover now might save Fermat, who was surely entering Paris, but it could expose their refuge. To stay silent might condemn them all.",
      "",
      "His hand hovered over the organ keys. “Forgive me,” he whispered — then pressed a chord of deep resonance: C, E, G, C′ — the encoded bell-signal known only to those bound by the Stones.",
      "",
      "Across the city, in the chaos of carriage wheels and street cries, a single vibration rippled through the air — a harmonic whisper reaching toward Fermat’s red stone.",
      "",
      "The Keepers exchanged a glance.",
      "“So it begins,” said Apollonius quietly.",
      "“The convergence,” added Diophantus.",
      "",
      "And somewhere beyond the cloister walls, the next alliance was already forming."
    ],
    "image": "/story/algebraic-avengers/beat_43.png",
    "imageAlt": "Inside the cloister, Father Mersenne stands before a great organ, pressing a resonant chord as the four Keepers watch, a false monk revealed among the shadows.",
    "caption": "As the Red Order closes in, Mersenne detects a false harmony — the enemy within the cloister — and sends an encoded bell-signal across Paris to warn Fermat and summon the coming alliance."
  },
  {
    "id": "algebra-avengers-beat-44",
    "pathSlug": "algebra-avengers",
    "sequence": 44,
    "context": "problem",
    "problemOrder": 43,
    "problemId": "algebra-avengers-advanced-1-problem-13",
    "title": "The Empty Coach",
    "narrative": [
      "“There it is,” hissed the first man in the red coat.",
      "",
      "The lead henchman straightened, a thin smile spreading across his scarred face. At last, something had gone according to plan. His informants had been right — the Paris coach rounding the bend carried Pierre de Fermat. And with him, the red stone.",
      "",
      "“Hold your positions,” he ordered, voice sharp and low. “No mistakes. Not this time.”",
      "",
      "The men crouched behind barrels and broken carts along the narrow street. A damp chill hung in the air, the scent of soot and rain mixing with the musk of horses. Each second dragged, the creak of wooden wheels louder than their own breathing.",
      "",
      "When the coach drew within ten paces, the lead henchman raised his hand. “Now!” he barked.",
      "",
      "A blur of red coats burst from both sides of the lane. “Surround them! Surround them!”",
      "",
      "The driver froze, reins slipping from his hands. “You — down!” the henchman barked, shoving him hard against the wall. The horses reared, hooves clattering on slick stone. Two men advanced toward the carriage door, muskets trembling in their grip.",
      "",
      "“Get him out!” shouted the leader.",
      "",
      "They hesitated — expecting at any moment for the door to fly open and resistance to begin. At last, one reached forward, fingers slick with sweat, and pulled the handle.",
      "",
      "The door creaked wide. Silence. Inside the dim carriage, the seat was empty — save for a single fashionable hat resting neatly on the cushion.",
      "",
      "The henchman’s smile vanished. The hat rocked gently as the carriage shifted, and beneath its brim glimmered a faint chalk symbol — a spiral traced from prime to prime, winding inward to nothing.",
      "",
      "“He’s gone,” whispered one of the men.",
      "",
      "The lead henchman clenched his jaw, staring at the spiral until the rain began to wash it away."
    ],
    "image": "/story/algebraic-avengers/beat_44.png",
    "imageAlt": "A rain-slick Paris street at dusk, Red Order henchmen surrounding an empty carriage as a single hat lies inside, marked with a faint chalk spiral.",
    "caption": "The Red Order intercepts Fermat’s coach — only to find it empty. A chalk spiral of primes left behind hints that the mathematician has already slipped beyond their grasp."
  },
  {
    "id": "algebra-avengers-beat-45",
    "pathSlug": "algebra-avengers",
    "sequence": 45,
    "context": "problem",
    "problemOrder": 44,
    "problemId": "algebra-avengers-advanced-1-problem-14",
    "title": "The Keeper Revealed",
    "narrative": [
      "Fermat stumbled through the rain-slick streets, breath misting in the cold air as he struggled to keep pace with the stranger who had hauled him from his carriage only minutes earlier.",
      "",
      "“Where are we heading?” he panted.",
      "",
      "The man said nothing, striding ahead with long, deliberate steps, his boots striking the cobblestones in a steady, rhythmic pattern — almost mathematical in its precision.",
      "",
      "The rain thickened, drumming on rooftops and spilling in silver sheets across the narrow lane. Fermat stopped beneath the awning of a shuttered café, chest heaving. “I’ll be damned,” he muttered, straightening his coat. “I’ve had enough of this absurd chase.”",
      "",
      "The stranger turned. His eyes caught the lantern light — calm, analytical, yet piercing. He studied Fermat as though testing an equation.",
      "",
      "“Well?” Fermat demanded, anger rising. “You drag me through half the city like a common fugitive. What is the meaning of this intrusion?”",
      "",
      "The man’s voice, when it came, was steady and deep, carrying the clarity of logic itself. “Time is short, and danger is near. Answers will come at the appointed moment.”",
      "",
      "Fermat’s temper flared. “At least tell me who you are, sir, before I decide whether to trust you or throttle you!”",
      "",
      "The stranger inclined his head slightly. “I am Euclid of Alexandria — keeper of the stone you carry in your pocket. There is much to explain, but not here.”",
      "",
      "Fermat froze, hand instinctively brushing against the red stone in his coat.",
      "",
      "“Now onward,” said Euclid, already turning into the mist.",
      "",
      "Fermat followed, half in disbelief, half compelled — a man of reason stepping into a mystery older than proof itself. The pulse of the stone against his chest, that had once seemed random, now beat in perfect synchrony with the man’s stride."
    ],
    "image": "/story/algebraic-avengers/beat_45.png",
    "imageAlt": "Pierre de Fermat stands beneath a café awning in the Paris rain, confronting a cloaked stranger whose calm gaze reflects the light of a nearby lantern.",
    "caption": "Dragged from his carriage and pursued through the rain, Fermat meets his rescuer — Euclid of Alexandria, keeper of the red stone — and follows him into the mist toward destiny."
  },
  {
    "id": "algebra-avengers-beat-46",
    "pathSlug": "algebra-avengers",
    "sequence": 46,
    "context": "problem",
    "problemOrder": 45,
    "problemId": "algebra-avengers-advanced-1-problem-15",
    "title": "Old Friends and Strange Forces",
    "narrative": [
      "Fermat sat hunched on an old wooden chair, gnawing absently at a piece of bread.",
      "",
      "“I should be hungry,” he thought. “After all that’s happened, I should feel something.”",
      "",
      "But his mind would not still. It spun in feverish circles, tracing patterns that refused to settle into sense. The logic of it all escaped him — and that, above all, was what he despised most.",
      "",
      "A hand touched his shoulder. He jumped, the bread tumbling from his grasp.",
      "",
      "“My old friend,” came a warm, familiar voice. “I see you are enjoying a fine feast!”",
      "",
      "Fermat turned, eyes wide. There, grinning in the flickering firelight, stood René Descartes. For a moment, disbelief froze him — then, despite himself, he smiled. “René… what a surprise indeed.”",
      "",
      "The relief was fleeting. The confusion that had been ebbing surged back like a tide.",
      "",
      "“Be at peace, my friend,” Descartes said softly, taking a seat opposite him. “Do not hunt for all the answers when you hold only a few of the facts. Clear your mind. Clarity begins with stillness.”",
      "",
      "Fermat leaned forward. “But where are we, René? What is happening?”",
      "",
      "Descartes’ expression faltered. Pity flickered across his sharp features — pity for a man whose reason was meeting the edge of its limits.",
      "",
      "“We are beneath the Sainte-Chapelle, mon ami. The chapel’s old cellar — though not by accident. Why we are here…” He sighed. “That is another question entirely. Strange forces move, and we are but caught in their current.”",
      "",
      "Fermat rubbed his temples, voice trembling. “A man called himself Euclid to me — pulled me from my carriage. He knew of the stone.”",
      "",
      "“Yes,” Descartes replied, his tone grave. “As I said… strange forces indeed.”"
    ],
    "image": "/story/algebraic-avengers/beat_46.png",
    "imageAlt": "Fermat sits in a dimly lit cellar beneath Sainte-Chapelle, startled as René Descartes appears beside him, the flicker of torchlight revealing a mix of warmth and unease.",
    "caption": "In the hidden cellar beneath Sainte-Chapelle, Fermat reunites with Descartes — an old friend bringing calm counsel amid growing confusion and unseen forces."
  },
  {
    "id": "algebra-avengers-beat-47",
    "pathSlug": "algebra-avengers",
    "sequence": 47,
    "context": "problem",
    "problemOrder": 46,
    "problemId": "algebra-avengers-boss-1-problem-1",
    "title": "The Fellowship of Reason",
    "narrative": [
      "“The cards are now on the table, my friends,” said Father Marin Mersenne, his voice resonating through the vaulted cellar of the Sainte-Chapelle. “Though many still lie face-down.”",
      "",
      "Before him stood a gathering beyond reason — Pierre de Fermat, René Descartes, Sophie Germain, Karl Weierstrass, and the four ancient Keepers, their forms half-lit by the amber glow of the torches. Centuries of thought, bound together in one impossible room.",
      "",
      "“None of us,” continued Mersenne, “can claim to understand the mechanism that has drawn us across time and death itself. Perhaps that understanding lies beyond the limits even of our logic. Only Archimedes, who set this design in motion, might have known the method.”",
      "",
      "A ripple of murmurs moved through the assembly. Fermat leaned forward, Sophie folded her arms, Weierstrass frowned in thought — minds searching instinctively for proof where none could yet be found.",
      "",
      "Mersenne raised a hand. “Let that puzzle rest. For now, let us take it as axiomatic that we are here — and that the Stones are accounted for. From this base, we must proceed as reason dictates: each of us a term in the equation to restore balance.”",
      "",
      "He paused, his expression hardening. “Make no mistake. What we face is no mere curiosity of fate. There has been an assault on reason itself — an assault on logic, on freedom, on the very right to think. The people’s minds are chained by greed and shadowed by power. Knowledge has been bartered for profit, understanding for control.”",
      "",
      "The torches flickered; the air seemed to tighten.",
      "",
      "“Archimedes foresaw this. He scattered the Stones not in despair, but in faith — faith that those who valued truth above comfort would find one another when the world most needed them. We may not yet see the full pattern, nor the final theorem, but it exists. And together,” he said, voice rising, “we shall solve it.”",
      "",
      "The chamber fell silent. For the first time in centuries, reason had its fellowship."
    ],
    "image": "/story/algebraic-avengers/beat_47.png",
    "imageAlt": "In the flickering light of the Sainte-Chapelle cellar, Father Mersenne stands before an assembly of mathematicians from across the ages, their faces illuminated with resolve.",
    "caption": "In a hidden chamber beneath Paris, Mersenne unites minds across centuries — the first Fellowship of Reason — to defend logic and freedom from the forces of ignorance and greed."
  }  
];
