import type { StoryBeat } from './types';

export const storyBeats: StoryBeat[] = [
  {
    id: 'algebra-avengers-intro',
    pathSlug: 'algebra-avengers',
    sequence: 1,
    context: 'path',
    title: 'The Order of the Olympiad has fallen',
    narrative: [
      'Archimedes slumps on the hard, cold floor of a dungeon at ‘The Blackhouse’.',
      'Each breath is a painful effort now.  He knows the end is nigh.',
      'The Red Baron stands over him, smirking menacingly. "Not so rational or logical now are you old man.  Fool!"',
      '"So naive. So stupid. Your stones of Logic, Rigor, Curiosity and Persistence will be mine soon enough.  Your order is finished!"',
      'The Red Baron ticks an item off his checklist and slinks into the shadows',
      'Archimedes falls down onto his side.  "The rational mind is never gone ... it can rest, but is never defeated.  Others will come.  All shall be restored."',
      'And with that, the great man exhales for the last time.',
    ],
    image: '/story/algebraic-avengers/beat_1.png',
    imageAlt: 'Archimedes dies.',
    caption: 'The greatest mathematician of antiquity is dead. Irrationality reigns.',
  },
  {
    id: 'algebra-avengers-problem-1',
    pathSlug: 'algebra-avengers',
    sequence: 2,
    context: 'problem',
    problemOrder: 1,
    problemId: 'algebra-avengers-basic-1-problem-1',
    title: 'Carl Friedrich Gauss',
    narrative: [
      'The dust swirls in the long silence. A cool breeze floats through the stable, gently tugging Carl Friedrich Gauss back into the present.',
      '"How is that possible? The realm cannot go on without The Order ... without Archimedes.  What are we to do? Chaos will consume us all!"',
      'Sir Euler listens calmly to his young protege. The aging Knight has no answers. But he knows they will come.',
      '"The Red Baron is stronger than we realised. Stronger than we ever feared possible. Our agents are searching for more information about the Stones of Enlightment as we speak."',
      '"But do not fear Carl Friedrich. Be calm. Be vigilant. Our path will appear ... when we are ready to see it."',
    ],
    image: '/story/algebraic-avengers/beat_2.png',
    imageAlt: 'Introducing Carl Friedrich.',
    caption: 'Powerful emotions stir as the young squire learns of the fall of the Order of the Olympiad.',
  },
  {
    id: 'algebra-avengers-problem-2',
    pathSlug: 'algebra-avengers',
    sequence: 3,
    context: 'problem',
    problemOrder: 2,
    problemId: 'algebra-avengers-basic-1-problem-2',
    title: 'Princess Emmy Noether',
    narrative: [
      '"Some answers must lie in here", Emmy sighed.  6 hours had passed since she entered to library since learning of death of Archimedes.',
      '"I will not rest until I find some understanding". What was this ‘Order of the Olympiad‘? What was its purpose and why had the Red Baron sought to destroy it.',
      'Emmy was the only child of King Thales and Queen Mathilde. She was 1st in line to the throne and her life felt like a series of formal functions and rules of etiquitte.',
      'But mathematics had always been her passion ever since she could remember. She soaked up all she could from he daily sessions with her tutor, Ms. Kovalevskaya.',
      'And now she felt a cool tingle of excitement. The moment had come to apply all that she had learned.',
    ],
    image: '/story/algebraic-avengers/beat_3.png',
    imageAlt: 'Introducing Emmy.',
    caption: 'Princess Emmy pores over a weighty, dusty tome ... The Paths of the Order by Archimedes of Syracuse.',
  },
  {
    id: 'algebra-avengers-problem-3',
    pathSlug: 'algebra-avengers',
    sequence: 4,
    context: 'problem',
    problemOrder: 3,
    problemId: 'algebra-avengers-basic-1-problem-3',
    title: 'The squire is summoned.',
    narrative: [
      '"Apologies for the late hour Squire Gauss.  She said you must come immediately."',
      'Carl Friedrich was just about to turn in for the night when he was startled by 2 men carrying torches entering the stable.',
      'He had been provided with a small cottage by Sir Euler when he took up his tutelage, however he preferred to sleep in a bunk near the horses.',
      '"The Princess? But why?", Carl stammered.',
      '"We have no answers, only orders Squire.  We apologise again, but let us make haste. She said the matter is of the utmost importance."',
      'Carl Friedrich felt a chill of anxiety. Had something happened at home? His family was reliant on his meagre wages and they had foregone much to get him to this position. Every day had been a struggle since Carl‘s father died.',
      '"Understood.  I will be ready in 2 moments."',
    ],
    image: '/story/algebraic-avengers/beat_4.png',
    imageAlt: 'Carl Friedrich called to the castle.',
    caption: 'Carl Friedrich is startled at the stables.',
  },
  {
    id: 'algebra-avengers-problem-4',
    pathSlug: 'algebra-avengers',
    sequence: 5,
    context: 'problem',
    problemOrder: 4,
    problemId: 'algebra-avengers-basic-1-problem-4',
    title: 'A midnight meeting.',
    narrative: [
      '"Yes, he is on his way My Lady."',
      '"Time is of the essence Ladbrook. How can it take this long!", Emmy said impatiently.',
      '"They will be here shortly My Lady. The creek down near the top stables flooded last week. It is slow going through there."',
      'Emmy paced back and forth in front of the old chapel‘s steps. Today felt like a blur. Nothing would come into focus.',
      '"Why on earth would the name of a poorly uneducated Squire of low blood be scribbled in a margin on the 3rd last page of the book?", she thought to herself.',
      'As this question siwrled around and around in her mind, the faint sound of footsteps could be heard. Then 3 men came around the corner and entered the cloister. One of them was a rather scruffy, scared looking lad whose forehead glistened with sweat.',
      'Emmy felt her jaw clench. "Surely not", she mumbled under her breath.',
    ],
    image: '/story/algebraic-avengers/beat_5.png',
    imageAlt: 'Princess Emmy waits for Carl Friedrich.',
    caption: 'Princess Emmy paces back and forward impatiently just outside the chapel.',
  },
  {
    id: 'algebra-avengers-problem-5',
    pathSlug: 'algebra-avengers',
    sequence: 6,
    context: 'problem',
    problemOrder: 5,
    problemId: 'algebra-avengers-basic-1-problem-5',
    title: 'Questions ... but no answers.',
    narrative: [
      '"Thank you for coming Squire Gauss. This matter is most urgent."',
      '"Happy to be of service My Lady. No hour is too late", Carl Friedrich lied.',
      '"Let me get to the point.", Emmy said curtly, handing Carl a book entitled ‘The Order of Olympiad‘.',
      '"Why does your name appear in hand-written in this book? Page 441.", she enquired impatiently.',
      '"No idea", Carl stammered nervously.  "I have never seen this book before."  He glanced down at the beatifully written text on its leather cover. "The Order the Olympiad?"',
      '"You know of it?", Emmy probed.',
      '"Yes. And I know that Archimedes was captured during the winter and has now died. I know the Order has fallen. Sir Euler told me this afternoon.  But I have never seen this book. My father taught me of the Order when I was a boy."',
      'Emmy was silent. She gathered her thoughts. Could she believe this boy. This young man. He seemed honest.',
      '"Ok.", she replied. She would play her cards close to her chest and try to catch him flinch. "What do you know of mathematics?"',
    ],
    image: '/story/algebraic-avengers/beat_6.png',
    imageAlt: 'Princess Emmy questions for Carl Friedrich.',
    caption: 'Princess Emmy questions Carl Friedrich about the appearance of his name in the Order of Olympiad.',
  },
  {
    id: 'algebra-avengers-problem-6',
    pathSlug: 'algebra-avengers',
    sequence: 7,
    context: 'problem',
    problemOrder: 6,
    problemId: 'algebra-avengers-basic-1-problem-6',
    title: 'A strange sense of connection.',
    narrative: [
      'Carl Friedrich walks alone under the moonlight, his boots crunching softly against the gravel path. The air is cool, and the night insects sing along the stream beside him.',
      'His thoughts race, replaying the strange encounter with Princess Emmy. “She was holding something back,” he murmurs, brow furrowed. “What on earth does that book have to do with me? I never even met Archimedes … all I know of him and the Order is what my father taught me during our lessons."',
      'Crossing the small stone bridge leading back to the stables, Carl feels a shiver course through him, not from the night air but from a strange, heavy sense of connection - like unseen eyes watching, or an echo of Archimedes’ presence carried in the current below. The moonlight glimmers on the water as if whispering secrets he cannot yet understand.',
      
    ],
    image: '/story/algebraic-avengers/beat_7.png',
    imageAlt: 'Carl Friedrich walks home, thoughts swirling through this mind.',
    caption: 'Carl Friedrich walks home, thoughts swirling through this mind.',
  },
  {
    id: 'algebra-avengers-problem-7',
    pathSlug: 'algebra-avengers',
    sequence: 8,
    context: 'problem',
    problemOrder: 7,
    problemId: 'algebra-avengers-basic-1-problem-7',
    title: 'A fight for reason?',
    narrative: [
      'The first light of dawn creeps into the stable yard, pale and cold. Carl Friedrich rises after a restless night, his mind still crowded with questions. He moves with quiet purpose, leading Thunder - the proud steed of Sir Euler - into the aisle. The horse snorts gently, steam rising from its nostrils in the morning chill, as Carl rubs him down with steady strokes.',
      'As his hands work the brush through Thunder’s coat, Carl drifts back to memories of his father. Long evenings bent over parchment, ink smudged on their fingers, as they worked through mathematical problems by candlelight. His father’s eyes always burned with something more than simple curiosity - something Carl only half understood. Each lesson carried a story of the Order of the Olympiad, of Archimedes’ daring, of the struggle to preserve reason.',
      '“Fight for reason. Defend rationality, son,” his father had always insisted, voice steady with conviction. Carl remembered smiling at the time, thinking it was nothing more than romantic idealism. But now, in the quiet dawn, with the strange weight of Emmy’s summons still pressing on him, those words seemed less fanciful - and more like a warning.',
      
    ],
    image: '/story/algebraic-avengers/beat_8.png',
    imageAlt: 'Carl Friedrich remembers.',
    caption: 'Carl Friedrich is lost in this thoughts. Recalling his father’s words.',
  },
  {
    id: 'algebra-avengers-problem-8',
    pathSlug: 'algebra-avengers',
    sequence: 9,
    context: 'problem',
    problemOrder: 8,
    problemId: 'algebra-avengers-basic-1-problem-8',
    title: 'A father’s farewell.',
    narrative: [
      'A light rain falls as mourners gather in the small churchyard. Dorothea Gauss clutches her shawl, her eyes red with grief as she and her family stand beside the casket. Father Ceva offers words of comfort, his voice solemn under the gray sky.',
      'Carl stares at the coffin of his father, Gebhard Gauss—a stern man who rarely showed affection, yet whose sudden passing left a void too deep to measure. Beside him, Uncle Friedrich bows his head, the Duke of Brunswick’s support behind him, but even that seemed fragile against the weight of loss.',
      'Carl’s mind drifts as rain collects on his mat of brown hair and dampens his coat. His father’s words echo again: “Fight for reason. Defend rationality, son.” For the first time, Carl does not dismiss them as romantic ideals. He feels the charge settle on his shoulders, heavy and inescapable. “Yes, Father,” he whispers silently, “I will.”',
    ],
    image: '/story/algebraic-avengers/beat_9.png',
    imageAlt: 'Carl Friedrich at his father’s funeral.',
    caption: 'Carl remembers his father’s final lesson as the rain falls.',
  },  
  {
    id: 'algebra-avengers-problem-9',
    pathSlug: 'algebra-avengers',
    sequence: 10,
    context: 'problem',
    problemOrder: 9,
    problemId: 'algebra-avengers-basic-1-problem-9',
    title: 'A mystery visitor.',
    narrative: [
      'Carl and Dorothea sat at the kitchen table after the funeral. Their modest home was tidy and cosy, yet tonight it felt heavy with silence. The only sound was the faint tick of the wall clock.',
      '"Mother, did Father always have such a passion for mathematics?" Carl asked quietly. "He was so driven with his lessons. I never really understood why."',
      'Dorothea shook her head gently. "Oh no, dear. Your father was a simple man. It all changed after that strange gentleman visited us, when you were barely able to walk. Soon after, he began borrowing all sorts of books on mathematics from the library."',
      '"Books?" Carl frowned.',
      '"Yes. I asked him why, and he only smiled and said it was to strengthen his reasoning. He never spoke more of it, but I saw a fire in him I had never seen before."',
      'Carl lifted his teacup, staring into the dark liquid. He drank slowly, but the warmth did little to ease the chill of new questions rising within him.',
    ],
    image: '/story/algebraic-avengers/beat_10.png',
    imageAlt: 'Carl and his mother Dorothea at the kitchen table.',
    caption: 'Dorothea recalls the mysterious visitor who sparked Gebhard’s passion for mathematics.',
  },  
  {
    id: 'algebra-avengers-problem-10',
    pathSlug: 'algebra-avengers',
    sequence: 11,
    context: 'problem',
    problemOrder: 10,
    problemId: 'algebra-avengers-basic-1-problem-10',
    title: 'A hidden riddle.',
    narrative: [
      'Emmy had read through every page of the great tome. Twice. After her meeting with Carl Friedrich, she could think of nothing else. “I know this is important… but why?” she whispered. For hours she had traced the passages about the Order and their devotion to problem-solving, yet nowhere did it explain why the name of a Squire Gauss was scrawled in its margin.',
      'Her eyes burned with fatigue. With a sigh, she closed the heavy cover and heaved the volume back toward its place on the shelf. As she slid it into place, something shifted. A thin, rectangular slip of parchment edged its way from beneath the spine, fluttering onto the floor.',
      'Emmy bent down, heart quickening. On the slip, in faded ink, was written a riddle:',
      '“Red lies at the ratio 3:2, when all of their prayers align.”',
      'She stared at the words, a shiver running down her arms. The message was no accident. It was meant for her to find.',
    ],
    image: '/story/algebraic-avengers/beat_11.png',
    imageAlt: 'Princess Emmy in the candlelit library discovering a hidden parchment.',
    caption: 'In the quiet library, Emmy uncovers a mysterious riddle hidden in the spine of the book.',
  },  
  {
    id: 'algebra-avengers-problem-11',
    pathSlug: 'algebra-avengers',
    sequence: 12,
    context: 'problem',
    problemOrder: 11,
    problemId: 'algebra-avengers-basic-1-problem-11',
    title: 'The Baron’s fury.',
    narrative: [
      '“What do you mean your men can’t find them!” The Red Baron’s voice cracked like a whip, echoing through the vaulted hall. He slammed his gauntleted hand on the oak table, the sound rattling goblets and scattering parchments. His face blazed crimson, eyes burning with fury so intense that even his lead henchman flinched.',
      '“We know he had the Stones of Enlightenment! Your scouts said they were in his possession the day before we seized him,” the Baron snarled.',
      'The henchman bowed his head, words tumbling nervously. “They were there, my Lord… but they are not there now. The place has been cleared out.”',
      'A suffocating silence followed, heavy as the storm before a thunderclap. The soldiers in the shadows dared not breathe. The Red Baron’s glare lingered on his trembling servant, the air alive with the threat of sudden, violent reprisal.'
    ],
    image: '/story/algebraic-avengers/beat_12.png',
    imageAlt: 'The Red Baron slams his hand on a war table in a vaulted hall as soldiers cower.',
    caption: 'The Red Baron’s fury fills the hall with dread.',
  },  
];
